### ISSUE TITLE
Consider using uson instead of json for better performance, and add uson as optional dependency 

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#103]
uson: https://pypi.org/project/ujson/

seems to be a drop-in replacement for the stdlib json pkg.

pydantic uses it as well if available.

However, last release of ujson was Jan 2016. So maintenance may be suboptimal.

**Comment by khaeru** [comment]
See [this comment](https://github.com/dr-leo/pandaSDMX/issues/104#issuecomment-523940222) on #104 for a discussion of "better performance".

**Comment by dr-leo** [comment]
There is a lot to say on Performance of various json implementations. And the Overall cost Impact of parsing json on pandasdmx may or may not be significant.  

This can be re-opened once json is used more broadly alongside XML.
