### ISSUE TITLE
Improve performance of ItemScheme

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#104]
Searching in, and appending to Item and ItemScheme has poor Performance due to the use of list instead of dict or set. In v0.9, ItemSchemes were DictLike instances with item id as dict keys. As certain codelists are very Long (I've seen more than 50k items), poor Performance is a concern. My first Suggestion would  be to borough some of the v0.9 Code while keeping the useful parent-child relationship.

**Comment by khaeru** [comment]
Can you give an example of a specific case where this takes too long?

**Comment by dr-leo** [comment]
Sorry. I can't as I don't know what you mean by too long. I've just
found a number of minor Code Quality issues in model.ItemScheme which
Impact Performance and stability. E.g.:

* Long lists are ill-suited for linear searching
* Attribute Access should be simplified by using __getattribute__ as
it is called only upon AttributeError
* drop recursive search in __contains__ as children are always
contained in the same ItemScheme as its parents. This may even yield
inconsistent results when __contains__ is called by more complex
iterators, e.g. when an item is child to multiple parents.

Btw: Are you Aware of any practical example of hierarchical Code lists?

Moreover, I think ItemScheme and its subclasses should accept any
Iterable rather than just List.


* __

**Comment by khaeru** [comment]
> Sorry. I can't as I don't know what you mean by too long.

You say "has poor Performance", "poor Performance is a concern", "which Impact Performance."

In software development, performance must be _quantified_ by some metric, such as:
- time,
- memory use,
- disk usage,
- network traffic or bandwidth

…required to accomplish a certain task.

"poor performance" implicitly means, "I believe that doing [operation X] should take no more than T1 seconds; instead it takes T2, which is greater than T1—i.e. **too long**."

Similarly, "Impact Performance" implicitly means "doing [operation X] in [way A] takes T1 seconds; doing it in [way B] takes T2 [> T1] seconds, and T1 is acceptable whereas T2 is not."

Python has [built-in features](https://docs.python.org/3/library/timeit.html) for timing small bits of code, such as the look-ups you refer to.

Without (a) a specific example of code ("operation X"), and (b) specific, i.e. quantified, values for its current and desired performance (T1 and T2), there's no way to decide when the issue has been addressed, or how to prioritize it. The same applies over in #103.

> Btw: Are you Aware of any practical example of hierarchical Code lists?

ISTAT does, I believe.

> ItemScheme and its subclasses should accept any Iterable rather than just List.

This is a convenience that could be added as an enhancement. But, again, let's please try to use separate issues for atomic topics.

**Comment by dr-leo** [comment]
Largely addressed by #108.
