### ISSUE TITLE
ISTAT IndexError list index out of range

### ISSUE THREAD

**Issue by almen3001** [dr-leo/pandaSDMX#107]
Hi,
I was successfully using the following code, but it started to give error in July.
Any help is appreciated.
Thanks
Alessandro

**Code**: 
istat = pandasdmx.Request('ISTAT')
foi_data_response = istat.data(resource_id='169_745')
foi_df = foi_data_response.write()

**Error**:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-50bf030b714b> in <module>
----> 1 foi_df = foi_data_response.write()

\site-packages\pandasdmx\api.py in write(self, source, **kwargs)
    569         if not source:
    570             source = self.msg
--> 571         return self._writer.write(source=source, **kwargs)
    572 
    573     def write_source(self, filename):

\site-packages\pandasdmx\writer\data2pandas.py in write(self, source, asframe, dtype, attributes, reverse_obs, fromfreq, parse_time)
    107                 series_list = list(s for s in self.iter_pd_series(
    108                     iter_series, dim_at_obs, dtype, attributes,
--> 109                     reverse_obs, fromfreq, parse_time))
    110                 if dtype and attributes:
    111                     # series_list is actually a list of pairs of series

\site-packages\pandasdmx\writer\data2pandas.py in <genexpr>(.0)
    105         else:
    106             if asframe:
--> 107                 series_list = list(s for s in self.iter_pd_series(
    108                     iter_series, dim_at_obs, dtype, attributes,
    109                     reverse_obs, fromfreq, parse_time))

\site-packages\pandasdmx\writer\data2pandas.py in iter_pd_series(self, iter_series, dim_at_obs, dtype, attributes, reverse_obs, fromfreq, parse_time)
    147             # Generate the 3 main columns: index, values and attributes
    148             obs_zip = list(zip(*series.obs(with_values=dtype,
--> 149                                            with_attributes=with_obs_attr, reverse_obs=reverse_obs)))
    150             # Are there observations at all?
    151             if obs_zip:

\site-packages\pandasdmx\reader\sdmxml.py in iter_generic_series_obs(self, sdmxobj, with_value, with_attributes, reverse_obs)
    364                 obs_dim = self._paths['generic_series_dim_path'](obs)[0]
    365                 if with_value:
--> 366                     obs_value = self._paths['obs_value_path'](obs)[0]
    367                 else:
    368                     obs_value = None

IndexError: list index out of range

**Comment by dr-leo** [comment]
I recommend trying the development version on guithub rather than version 0.9. The forthcoming release will be a substantial rewrite.

**Comment by almen3001** [comment]
Thanks dr-leo
I was not successful with the development version. Anyway I've been able to solve the problem filtering data:

istat = pandasdmx.Request('ISTAT')
foi_data_response = istat.data(resource_id='169_745', , key='M.00ST.IT.4.')
foi_df = foi_data_response.write()

it was enough for my purposes.
Thanks
Alessandro
