### ISSUE TITLE
Clean-up #108

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#111]
#108 was merged without code review.

Some things, that would have been picked up in a review, need to be fixed:
- Convenience methods ItemScheme.extend and ItemScheme.append require docstrings.
- Docstrings must be [correctly formatted](https://numpydoc.readthedocs.io/en/latest/format.html) for ItemScheme (class docstring) and ItemScheme.\_\_contains__. Namely:
  - Enclose in `"""`, not `'''`
  - First line begins after the `"""` with no whitespace and ends short of column 80.
  - There is a blank line following the first line.
  - The long-description is wrapped at column 80.
  - Parameters are documented.
- Test coverage was decreased; additional tests are required to cover new functionality.
- `pip install -U pip` in travis.yml is probably extraneous (though probably also harmless) and could be removed.

**Comment by dr-leo** [comment]
'pip install -U pip' is recommended in travis docs and a recent blog post.

I will Focus my scarce Resources on reviewing the Code base.

A PR remediating on Test coverage and doc string syntax would be appreciated.
