### ISSUE TITLE
Split remote tests to Travis ‘cron’ build

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#115]
As seen in #112/#113, unpredictable changes in the features/extent of data provided by remote data sources can cause CI to break.

We want to keep on top of changes to sources so that all the claimed support is in fact available. But these often get in the way of quickly handling unrelated issues.

To this end, one improvement could be:
- Split the test suite in two: (a) tests of specific data sources, (b) and all other tests.
- Run (a) via a [Travis ‘cron’ build](https://docs.travis-ci.com/user/cron-jobs/) that happens e.g. daily.
- Run (b) every time.

In this way, the quick tests (b) would be necessary for merging PRs; if a data source change caused remote tests (a) to start failing, we'd get prompt notifications, but it wouldn't interrupt other work.

Some issues/other points:
- Currently, certain variants of the SDMX-ML format are only tested **via** the remote tests. In other words, the ‘specimens’ (example files) included in `tests/data/` *do not include all the structures seen in real-world SDMX-ML messages from the supported sources*.

  For example, the sdmxml.Reader might pass on all the files in `tests/data/`, but fail on a file from, say, ILO.

  In order to ensure the (b) tests cover all these possibilities, we will need to add more specimens.
- We could consider splitting the test specimens and expected results to a different repository. That repo could then be included in the main one as a submodule; or downloaded on-demand by the test suite.

**Comment by dr-leo** [comment]
After a quick look at the cron build Feature, I am not entirely sure it will make us happy. First, we would Need to somehow tell travis to perform all Tests on a cron Event but only the non-remote ones on push Events. Maybe this can be done in travis.yml by issuing different command Options based on some condition. Even so, how are the results reported? If on github, the build Status from the previous push Event might be overwritten by the cron-triggered build. I guess this is not what we want. 

I would therefore float the following idea:
1. Modify travis.yml in the master branch so that remote Tests are skipped
2. create a "remote_test" branch with a modified travis.yml to run all the Tests
3. Merge master into remote_tests from time to time so as to perform remote Tests manually. This Comes at a cost: If travis.yml is modified on master, it will overwrite the Special Version on remote_test, unless there is a way to issue test-run commands conditionally based on the branch tag.

**Comment by khaeru** [comment]
> Even so, how are the results reported? If on github, the build Status from the previous push Event might be overwritten by the cron-triggered build. I guess this is not what we want.

It's independent for exactly these reasons. Cron builds are distinct from:
- ‘push’ builds, triggered by new commits on particular branches, e.g. master.
  - The build status badge in our README.md shows the latest master ‘push’ build status, so it is not affected by enabling cron builds; just like it is not affected by ‘pr’ builds (below).
- ‘pr’ builds, triggered by new commits on a PR branch.
   - So, again passing/failing cron builds will not affect work on PRs.

> First, we would Need to somehow tell travis to perform all Tests on a cron Event but only the non-remote ones on push Events. Maybe this can be done in travis.yml by issuing different command Options based on some condition.

Please see the section [“Detecting Builds Triggered by Cron”](https://docs.travis-ci.com/user/cron-jobs/#detecting-builds-triggered-by-cron) at the above URL.

It is easy to check this in Python code:
```python
@pytest.mark.skipif(os.environ.get('TRAVIS_EVENT_TYPE', '') != 'cron',
                    reason='Skipping remote tests for non-cron build.')
def test_remote_example():
    # etc.
```

This is the standard way to do it—without an extra branch or periodic manual merging.

**Comment by dr-leo** [comment]
OK. So do you intend to modify the remote marker used throughout the test Suite? If so this would seem very elegant. Can't judge if this would affect the command line Option to run with or without remote stuff.

Alternatively, you could add a small script wrapping the call to pytest and checking for the cron Event before calling pytest.main() with suitable Options.

**Comment by dr-leo** [comment]
I still like my idea of not changing a bit in the test Suite to avoid
These hiccups. A test-runner script tailored to travis is the easiest
and least intrusive Approach. And looking ahead, we don't want to
rewamp the test Suite once we decide to Switch CI Providers.

**Comment by dr-leo** [comment]
aI've set up a Weekly cron Job on Travis Building master each Wednesday morning.

TODO:

1. Decide whether to use a Shell script or python script which calls pytest passing desired Options based on the value of TRAVIS_EVENT_TYPE env var.
1. Add the script and adapt travis.yml

**Comment by dr-leo** [comment]
I'll open a PR adding a Python script for this.

**Comment by khaeru** [comment]
#131 closed this.
