### ISSUE TITLE
Pydantic version 1.0b1 Breaking Change as of 2019-10-01

### ISSUE THREAD

**Issue by razamu15** [dr-leo/pandaSDMX#121]
The change_exceptions function from pydantic.utils has been removed in version 1.0b1(https://pydantic-docs.helpmanual.io/changelog/#v10b1-2019-10-01)
) released on 2091-10-01. As a result the "setup.py install" installs the latest version which when attempting to use the library fails because it cannot get change_exceptions from pydantic.utils. From my quick test with yolk, it seems pydantic 1.2(newest post breaking change version) is the only version available for download with pip. 

(sorry for posting this here, saw #118 after creating this)

**Comment by razamu15** [comment]
(sorry for posting this here, saw #118 after creating this)

**Comment by khaeru** [comment]
@razamu15—no problem! Thanks for taking the plunge and making use of the beta version. We will try to wrap up #118 quickly.
