### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by KotZer** [dr-leo/pandaSDMX#13]
Include proxy parameter of requests.get in REST() class and consequently in Request()

**Comment by dr-leo** [comment]
Should be easy to implement. Maybe better in the Request constructer. 

PR for this?

**Comment by dr-leo** [comment]
You can already use a proxy by setting one of the environment variables
HTTP_PROXY or HTTPS_PROXY. This is a feature of 'requests'.

But exposing the optional 'proxies' parameter in pandasdmx is useful anyway.


Am 11.05.2015 um 10:50 schrieb KotZer:

**Comment by KotZer** [comment]
That's true, did not think about it... 
You can even generalize it and expose all **kwargs parameter of 'requests'.
Anyway thanks for this nice module

**Comment by dr-leo** [comment]
Great idea! I've just committed that. Does this work for you?


Am 11.05.2015 um 22:21 schrieb KotZer:

**Comment by KotZer** [comment]
Perfect thanks!
