### ISSUE TITLE
Travis build on python 3.8dev fails as pip install fails 

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#134]
As a temporary fix I suggest to avoid [failing builds](https://travis-ci.org/dr-leo/pandaSDMX/jobs/649273641) by simply not testing on py3.8dev.
  
Otherwise, the cron Job runs ok, the only failing test being fixed in #132.

**Comment by khaeru** [comment]
Whatever was causing this, it seems to have resolved itself. Closing for now.
