### ISSUE TITLE
Issues reading in SDMX files / updating guides

### ISSUE THREAD

**Issue by Quinten-gs** [dr-leo/pandaSDMX#140]
Dear, 

The goal of my project is to download all data from ESTAT and read it in directly using pandaSDMX as I want to do queries which are larger than the allowed number of datapoints. Therefore it is easier to go to https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?dir=data&filter=SDMX&sort=1&sort=2&start=all and download all SDMX. 

However I found it impossible to read in an SDMX file using pandaSDMX. I tried 

`import pandasdmx as sdmx`
`req = sdmx.Request(fromfile='aact_ali01.sdmx.zip')`
`req.data(agency='ESTAT',fromfile='aact_ali01.sdmx.zip').write()`

which returns an empty dictionary. 

Am I using the wrong syntax? How should I go about this? 

In some of the guides it is mentioned to use a sdmx.read_sdmx but this function is not available. The guides are thus outdated here and there. 

Best regards,
Quinten

**Comment by khaeru** [comment]
Thanks for your interest in the package! We are currently working on completing [version 1.0](https://github.com/dr-leo/pandaSDMX/milestone/1); I apologize this is taking a little while.

Can you please:
1. Install from the GitHub `master` branch, e.g. `pip install git+https://github.com/dr-leo/pandaSDMX@master#egg=pandasdmx`, and
2. Refer to the docs for the `master` branch, i.e. https://pandasdmx.readthedocs.io/en/master/, which were [recently thoroughly updated](https://github.com/dr-leo/pandaSDMX/pull/127)?

These two should be fully consistent with each other; but if they're not, please mention where.

Leave another comment to let us know if this lets you successfully handle the file you're working with.

**Comment by Quinten-gs** [comment]
Dear, 

Thank you very much for your quick response. I will enact these points and come back to you when I completed them. 

Best regards, 
Quinten

**Comment by Quinten-gs** [comment]
Attempting to install the pandasdmx from github prompted `ERROR: Package 'pandaSDMX' requires a different Python: 3.6.5 not in '>=3.7'`. Is 3.7 a fixed requirement or are there ways to circumvent this?

**Comment by dr-leo** [comment]
Hi,

pandasdmx 1.0dev requires python 3.7 or 3.8. I am afraid there is no Workaround.

that said, if you prefer giving v0.9 another Chance, you could unzip
the Archives before reading them. v0.9 had very limited support for
zipped sdmx files. Only when downloading from ESTAT These were
properly handled, not even when reading a locally saved file from
ESTAT.

That said, I also recommend v1.0dev, but the above comment on
unzipping mey apply as well.

**Comment by Quinten-gs** [comment]
Dear all, 

Many thanks for your help and recommendations. I tried unzipping but alas. It didn't work. 

I am attempting a different route. By specifying keys when pulling data with pandaSDMX, I try to split the data in smaller chunks. This might allow me to pull all data through pandaSDMX instead of downloading the SDMX files.

Best regards, 
Quinten

**Comment by khaeru** [comment]
@Quinten-gs [Anaconda](https://www.anaconda.com/distribution/) is a relatively beginner-friendly route that many people use to get an up-to-date Python installation, and should work on most systems.
