### ISSUE TITLE
Add performance profiling to the test suite

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#144]
In developing 1.0, questions of performance arose:
- #137: whether streaming HTTP content or read-before-parse is better (faster or lower-memory),
- #103: whether stdlib JSON is adequately fast compared to other parsers,
- etc.

Performance can be reliably improved by using the standard approach of profiling. To start, established tools could be added to the test suite/CI configuration, such as:
- [pytest-benchmark](https://pypi.org/project/pytest-benchmark/) ([docs](https://pytest-benchmark.readthedocs.io/en/latest/))
- [asv](https://github.com/airspeed-velocity/asv/), as used by e.g. [xarray](https://pandas.pydata.org/speed/xarray/) or [pandas](https://dev.pandas.io/docs/development/contributing.html#running-the-performance-test-suite) itself,
- [pytest-profiling](https://pypi.org/project/pytest-profiling/), or
- [any others](https://wiki.python.org/moin/PythonTestingToolsTaxonomy) that prove helpful.

This would allow to measure & examine concrete numbers for different operations, e.g.
- Memory usage for certain large data or structure messages.
- Time to (retrieve and) parse certain large messages.
- Network traffic to perform the automatic combo of (structure query + validated data query)—i.e. to limit the structure request(s) to the minimum necessary.
- Time to convert large model objects to pandas objects.

In turn, this would allow to:
- discuss desired performance: “Action X is undesirable because it (takes too long|uses too much memory|hammers servers unnecessarily); it should take less than (30 seconds|500 MB of memory|100 MB of network traffic)",
- check whether candidate code changes improve performance,
- ensure code changes don't introduce performance regressions.

Tagged 'help wanted'—this would be a welcome contribution from new pandaSDMX developers!

**Comment by dr-leo** [comment]
this would be great in many ways. I have no Knowledge on These Tools though. I consider it a nice-to-have for v1.0.

That said, the tool used for Pandas can't be that bad. So why not just use it?

**Comment by khaeru** [comment]
> So why not just use it?

Same reason: lack of time to apply the tools. I haven't used 'asv' in particular; and have only a little experience with pytest-benchmark.

Perhaps this can be one focus once 1.0 is released, i.e. as a way of making performance improvements towards 1.1 or 2.0? So we could target it at one of those two milestones.

**Comment by khaeru** [comment]
For reference, #162 contains one benchmark.

**Comment by dr-leo** [comment]
I have played around with the [cProfiler from the stdlib](https://docs.python.org/3/library/profile.html). It is probably a reasonable first step to get into profiling as asv and pytest-profiler are built on top of it. Hope I can share some results if I find the time to beautify them a bit.
