### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#145]
The [milestone for 1.0](https://github.com/dr-leo/pandaSDMX/milestone/1?closed=1) is 100% complete.

@dr-leo are there any other issues, that are missing from GitHub, yet must be addressed before the release?

**Comment by dr-leo** [comment]
Have to look into this more thoroughly. Off Hand:

1. Rethink subclassing pydantic.BaseModel: As seen before, this may create compat issues. 

I suggest 
* making a PR for pydantic to fix the issue marked as "want fix" to make copying behavior configurable, and
* consider another work-around for the infinite recursion. I was hoping to fix this by removing the recursive search in hierarchical codelists. Yet, 11 Tests fail when removing __getattr__ from the subclass. Haven't had the time to track this down.

The bare Minimum is to specify a Version range for the pydantic dep so that no newer Version can break our Code.

2. writer Output

I haven't checked for quite some time what the writer Returns, i.e. a multi-indexed series or dataframes. I acknowledge that users can get there using df.pivot etc. But I consider DataFrames that Mirror by default the layout in the SDMX data message as imparative. This feature from v0.9 should not be dropped in v1.0.
 

3. We Need a conda package

Need to check whether requests-cache is available on conda forge. Otherwise we might switch to a different Cache backend by Default. The requests docs list some wich are worth considering.

4. SDMXML Reader: _parse method

I struggle with the implementation, in particular using exceptions rather than if...else… for flow Control. I feel this makes debutting more difficult. But I haven't dug Deep enough to further Elaborate on this. I might be wrong here. I have never used exceptions for mere flow Control so far, and from a theoretical standpoint this is clearly not necessary.

5. Resolve references

the current Code assumes all references can be resolved within the same message, e.g., Concept-identity for dimensions, Dataflow.structure etc. Yet, this is not neccsrily the case. So how does the Code behave when a request for dataflow is made with references=None?

6. GUI by ading support for Intake or Jupyter widgets 

I consider this feature as important (there are open issues which I should work on). Usability is key. An intake Plugin should be doable, even for me ;-). I won't touch Jupyter Widgets though. But this is a nice-to-have for v1.0. If Intake support can be done in 50 lines, let's do it. If it turns out more difficult, let's Keep it for v1.1. 


7. Consider beta or even Alpha releases

I do think the Code is relatively stable mainly thanks to your efforts on the test Suite. Yet, Features may Change (see above).

Unfortunately, I have way too Little time than I wished to contribute.

8. Do not Pop from kwargs

I must admit I react allergically to These Patterns (I've remove one from remote recently). And wherever I see them I' chase them unless there is a compessling reason. The `assert len(kwargs)==0` pattern may be one reason *under specific conditions*.

**Comment by khaeru** [comment]
Thanks for this list! I will make additional comments to go through them one by one and either:
a. link them to existing issues/copy your remarks to those,
b. point out where new issues should be created, or
c. answer questions with explanations.

To phrase the core point differently: it has been >20 months since the last release, and all recent inquiries from users via GitHub have been resolvable by using the 1.0.0 beta code. From that metric, at least, the code appears to meet current needs.

Given limited time, I think it is most sustainable to:
1. Release 1.0.0 shortly to make it available for users.
2. Address open and new issues individually—according to how much time you have available to:
    a. file/describe them,
    b. discuss & identify solutions, and
    c. either implement them, or review my implementation in details.
3. Follow up with regular/frequent minor releases (1.1, 1.2, …) or major (2.0, 3.0, etc.) or patches (1.0.1, 1.1.1, etc.).

In particular, the 1.0 milestone has existed for almost 9 months. I'm very sympathetic re: limited time—also an issue for me. But since there has been not enough time in those 9 months to file/describe the above items and link them to the 1.0 milestone (2a), that implies (2b–c) will also take a long time, and a release could be delayed for another year or more. That seems not desirable.

For my part, I am able to commit to:
- handle the release process (3) as we deal with individual follow-up items—e.g. we could make a minor release after each of your bullet points to make them quickly available,
- respond to any user questions or bugs triggered by the 1.0 release, and
- help guide newcomers attracted by the release (e.g. #117) to make contributions; this could further reduce our workload.

**Comment by khaeru** [comment]
@dr-leo what are your thoughts on the above suggestion?

**Comment by dr-leo** [comment]
I am also sympathetic to releasing 1.0.0 rather sooner than later. That said, going through my list of issues which I consider desirable pre 1.0.0, I think 2 and 5 (writer should render DataFrames, and creating a conda package) are the most pressing. The more technical ones (re. streamlining code, GUI etc.) can probably be left for 1.x, unless someone comes up with a quick fix.

Not on my list but still important are #117 re. IMF data, and updating the docs.

Any thoughts?

**Comment by dr-leo** [comment]
I think we should do a 1.0.0a1 release just on GitHub and a related announcement on the Mailing list. The purposes of this is
* Experiment with the conda recipe
* Change the writer to Export data as dataframe according to the structure in the data message. I.e. dim_at_obs should be reflected in the dataframe's index, dimensions at series, Group or dataset Level should be in df.columns. The simplest, though somewhat inefficient way to achieve this would be some df.pivot or .reshape Operation in the writer. My Preference would be to construct a dataframe in the first place as in v0.9.
* update docs 
* fix IMF stuff

**Comment by khaeru** [comment]
> I am also sympathetic to releasing 1.0.0 rather sooner than later.

Thanks—glad we agree, and I think this is a reasonable prioritization to getting 1.0.0 released in a timely way.

For the items you identified as most pressing:

## Writer output

> I haven't checked for quite some time what the writer Returns, i.e. a multi-indexed series or dataframes. I acknowledge that users can get there using df.pivot etc. But I consider DataFrames that Mirror by default the layout in the SDMX data message as imparative. This feature from v0.9 should not be dropped in v1.0.

Currently the return values are:
1. Without attributes: pd.Series with pd.MultiIndex containing all Dimensions.
2. With some *attributes* argument: pd.DataFrame with 'value' column, plus one column per attribute; pd.MultiIndex containing all Dimensions.
3. With the *datetime* argument: always pd.DataFrame, with pd.DatetimeIndex or pd.PeriodIndex on one axis, and pd.MultiIndex with all other Dimensions on the other axis. I expanded the documentation [here](https://pandasdmx.readthedocs.io/en/master/walkthrough.html#convert-dimensions-to-pandas-datetimeindex-or-periodindex) with prose and example, and the API docs [here](https://pandasdmx.readthedocs.io/en/master/api.html#pandasdmx.writer.write_dataset), to describe the syntax. The features are a superset of what was possible in 0.9.

For the case of (1), the user can do something like:
```
series = sdmx.to_pandas(ds)
# DataFrame with Dimension and 'value' columns
df = sdmx.to_pandas(ds).reset_index()
```
Incidentally this also works for (2):
```
# DataFrame with 'value' and Attribute cols
df1 = sdmx.to_pandas(ds, attributes='dgso')
# DataFrame with Dimension, 'value', and Attribute columns
df2 = sdmx.to_pandas(ds, attributes='dgso').reset_index()  
```

If you like, I think it is a reasonable compromise to have an *rtype* argument that defaults to pd.DataFrame, so that the `.reset_index()` is performed automatically in (1); but if *rtype*=pd.Series, then it is skipped.

## Conda packaging (#83)
It is always possible to:
```
conda install pip
pip install pandaSDMX
```

I am, unfortunately, not an expert in conda packaging, so I am unable to help with this. It would need your effort or someone else to help.

However, as far as I understand, conda packaging can be added at any point, because it sort of wraps around an existing release of a package.

**Comment by khaeru** [comment]
> I think we should do a 1.0.0a1 release just on GitHub and a related announcement on the Mailing list.

Sorry, just saw this additional comment made while I was typing mine.

We already have beta-1 and beta-2 releases: https://pypi.org/project/pandaSDMX/#history
The next step would be a release candidate (1.0.0rc1).

**Comment by dr-leo** [comment]
Re. DataFrame vs. Series:

A single DataFrame with one value col and multiple attrib cols was not
posible in v0.9. Rather v0.9 returned separate DataFrames for values
and attribs. That said, I like the v1.0.0 Approach of combining values
and Attributes in a single DataFrame. `rtype` should stand for "return
type"? - Fine with me.

What I do not understand is how a cross-sectional dataset is rendered
by Defaultin v1.0.0. I have to say I feel strongly that by Default a
dataset should be rendered as received, i.e.:
* as a multi-indexed series if dim_at_obs="AllDimensions"
* as DateTime- or Period-indexed DataFrame of values if the message is
a TimeSeriesDataMessage, with all other dimensions arranged as
column-multi-inex, and
* as DataFrame indexed by the specified Dimension in case of a
cross-sectional DataMessage. The sample data comprises all These
cases.

I haven't used reset_index() so far, but will look into the current
behavior in more Detail and think About what could be a reasonable
trade-off between releasing in the not-too-far future and providing a
consistent user experience / not break existing Code which relies on
an intuitive layout of the rendered dataset.

**Comment by dr-leo** [comment]
On Releases: I forgot there is already a b1 and b2 release on pypi.
Even better. However, it seems a b3 release is warranted Prior to rc1.

**Comment by khaeru** [comment]
@dr-leo I noticed that you opened the six issues #152, #153, #154, #155, #156 and #157. Thank you for taking the time to test-drive the code and share some detailed observations.

To achieve the goal of a timely release of version 1.0, it is important to communicate which of these issues you feel need to be acted on before the release—and in contrast which can wait until a follow-up release like 1.1, 1.2, 2.0, etc. Please do this by associating them with the 1.0.0 milestone using the right sidebar. ([Here](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) is GitHub's help page about milestones.)

It would also help if you could edit your https://github.com/dr-leo/pandaSDMX/issues/145#issuecomment-603724278 above to link to the newly-created issues. Some items are mentioned in multiple comments on various issues and PRs; this reduces the work of tracking that they are linked and whether they are resolved.

**Comment by khaeru** [comment]
To update, since this issue was opened:
- #147 fixed by #148. 
- "Writer output" item from above https://github.com/dr-leo/pandaSDMX/issues/145#issuecomment-606557132 addressed by #151 **(needs review)**
- #152 discussed and closed.
- #153 fixed by #159.
- #154 fixed by #161.
- #155 discussed and closed.
- #156 discussed and deferred to v1.1.
- #157 fixed by #163.

Other items mentioned above, for which there were existing issues.

> 3. We Need a conda package

This is #83.

> 6. GUI by ading support for Intake or Jupyter widgets

This is #76.

Again, I don't have the knowledge or bandwidth for either of these, so I will put them to the 1.1 milestone for follow-up.

Is there anything else?

**Comment by dr-leo** [comment]
Thanks for the summary above. I can  think of two more things at this point:

* Check for any new data sources that might have set up an SDX service. I think there is one from Estonia.
* more importantly, and going beyond #151 which I hope to comment on / review soon: The current code base breaks every external package depending on pandasdmx. The main reason being the new behavior of the `to_pandas` convenience function, and the lack of a write() method for messages (in v0.9: : Response objects). So is it possible to add a write() method to all messages which essentially call api.to_pandas? This could help  some of the packages building on pandasdmx to transition to 1.0. I am agnostic on whether this can be done in #151 or warrants a separate issue/PR.

**Comment by khaeru** [comment]
> - Check for any new data sources that might have set up an SDX service. I think there is one from Estonia.

Please go ahead. I don't see this as a bug that should delay a release.

> - The current code base breaks every external package depending on pandasdmx.

Two points here, abstract of any specific features.
1. This is **the reason why** it must be a 1.0 release. See https://semver.org/#summary:
    > Given a version number MAJOR.MINOR.PATCH, increment the:
    > 1. MAJOR version when you make incompatible API changes,

   If there were no backwards-incompatible changes, it would merely be "v0.10".
   Labelling a release as 1.x versus 0.x, or 2.x versus 1.x specifically signals to users that there are changes in behaviour that they should study before updating their dependency.

2. What are these external packages? They are not mentioned anywhere in the code base.
   Per the above:
   - It's the responsibility of maintainers of downstream packages to manage their dependencies. For examples, authors writing packages that depend pandas had the choice to maintain a dependency on pandas 0.25 when pandas 1.0.0 was released, if the breaking changes were hard to deal with. It is not the responsibility of the pandas' authors to delay their 1.0.0 release because it might break our code.
   - If you have made a personal commitment to a specific maintainer to coordinate and avoid breakage, that must be explicitly stated somewhere, e.g. at a minimum with comments like `# for compatibility with 'package.name'` somewhere in the test suite. Without a specific mention somewhere, other developers cannot intuit it.
   - In any case, this is better handled by advising that other maintainer that "1.0 will be released soon, with backwards-incompatible changes; we suggest you pin to version `pandaSDMX < 1.0.0` for now, and here is a link to the documentation to suggest how to migrate your code."

**Comment by khaeru** [comment]
> the lack of a write() method for messages (in v0.9: : Response objects). So is it possible to add a write() method to all messages which essentially call api.to_pandas?

These methods exist. `to_pandas()` invokes these methods according to the type of object passed:
https://github.com/dr-leo/pandaSDMX/blob/3a9a3d23694c5d61878316f4a33cbd3aa3d1945a/pandasdmx/writer.py#L119-L174

Perhaps this was the same confusion as in #164, i.e. not using the latest `master` (although the code has been on `master` [for 12 months](https://github.com/dr-leo/pandaSDMX/blame/master/pandasdmx/writer.py#L120)…)

**Comment by khaeru** [comment]
> The [milestone for 1.0](https://github.com/dr-leo/pandaSDMX/milestone/1?closed=1) is 100% complete.

This milestone is again complete, with 5 issues + 7 PRs closed in the last 25 days. Some enhancements have been concretely assigned to the [1.1 milestone](https://github.com/dr-leo/pandaSDMX/milestone/2), to be worked on after 1.0.

In my view, the code is ready to release.

I could possibly compromise to make a [release candidate](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate) first, only if (a) there was a specific date chosen for the final release (e.g. +2 weeks) and (b) it was agreed the release is _code complete_ (no entirely new source code or features will be added; only fixes for bugs in the promised behaviour).

The code does _not_ meet common criteria for a [beta release](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta):
> …the software is feature complete but likely to contain a number of known or unknown bugs. Software in the beta phase will generally have many more bugs in it than completed software, speed or performance issues, and may still cause crashes or data loss.
