### ISSUE TITLE
Extend CI to Windows and optionally MacOS

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#147]
We currently run CI builds and Tests only in a Linux environment. This has lead to atleast weo subtle unnoticed Errors. See, in particular, #130 and #136. 

We should therefore consider adding Windows builds on travis, if supported at all, or, e.g., Appveyor or the recently launched GitHub CI Service. 

I have successfully used Appveyor in another Project, but have no experience with GitHub CI. That said, my time is very limited.

I would hope this can be done prior to relasing v1.0.0.

**Comment by khaeru** [comment]
> I would hope this can be done prior to relasing v1.0.0.

Please use the "Milestone" setting in the right sidebar to assign it to 1.0.0!

See #148 and the Travis docs for [macOS](https://docs.travis-ci.com/user/reference/osx/) and [Windows](https://docs.travis-ci.com/user/reference/windows/#supported-languages). On both of these platforms, Travis *does not* supply automatic configuration of different versions of Python, so we would need to configure it ourselves through .travis.yml, using homebrew (macOS) and chocolatey (Windows).

**Comment by khaeru** [comment]
> Please use the "Milestone" setting in the right sidebar to assign it to 1.0.0!

I've gone ahead and done this.
