### ISSUE TITLE
Migrate to travis-ci.com github app

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#149]
I have installed the travis GitHub app, the successor of GitHub Services, which we have been using so far.

I hope notifications on Windows and OSX builds will flow now. My Rough understanding is that travis-ci.org is now deprecated in favor of travis-ci.com. Hence, the links in README etc. should be updated.

**Comment by dr-leo** [comment]
Currently, pandasdmx does not appear in the repo list on travis-ci.com, all others do. I suspect that the pandasdmx Settings on travis-ci.org Need to migrated to travis-ci.com. This feature is in beta. I have submitted a request to join the beta.

that said, another Option might be to delete pandasdmx from travis-ci.org. Maybe this would allow Setting up the builds on travis-ci.org directly without Migration. All Settings would have to be redone. I am unsure About the best way Forward. Meanwhile I await approval for the beta to migrate.

**Comment by dr-leo** [comment]
The Migration to travis-ci.com has been completed.

As explained in [this guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration), only the links to travis-ci.org have to be updated as I hypothesized before. As we do not have any protected branches, no further changes are needed. It seems that even the cron Job Settings have been transferred.

**Comment by khaeru** [comment]
Great, thanks for doing this. I confirm I can see the project & settings at https://travis-ci.com/github/dr-leo/pandaSDMX/settings

And it seems the badge is available by changing .com to .org: ![](https://travis-ci.org/dr-leo/pandaSDMX.svg?branch=master)

So, will open a PR just to make that change & also check that it triggers a build reported back to GitHub.
