### ISSUE TITLE
Make tab completion on Request objects work correctly for resource types

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#153]
```python
from pandasdmx import Request
estat=Request('estat')
dsd_resp = estatastructure('une_rt_a')
```

When typing the last line, tab completion does not work, at least in a current version of ipython on Win10, py37. Better experience on other platforms??

I think I had open a similar issue months ago.

**Comment by khaeru** [comment]
For reference, I just located the docs for IPython tab completion: https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion

However, I'm a little confused. I guess there's a typo above and you meant this:
```python
dsd_resp = estat.datast<tab>
```
should complete to:
```python
dsd_resp = estat.datastructure()
```

Is that correct?

On my system, running the lines and then doing:
```
dsd_resp<tab>
```
…correctly brings up the attributes of the StructureMessage object.
