### ISSUE TITLE
urn and uri attributes of Maintainable/NameableArtefacts are None

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#154]
```python
dsd_resp=estat.datastructure('DSD_une_rt_a')
dsd_resp.structure.DSD_une_a.urn
```

This should be an str object containing the URN. Same for URI and possibly other attribs. Haven't checked the xml though.

**Comment by dr-leo** [comment]
Dimension objects have a proper urn though.

**Comment by khaeru** [comment]
Another subtle catch, thanks. Should be easy to write a test for this and ensure it's attached when parsing the message.
