### ISSUE TITLE
model.Dimension: Rename 'order' attribute to 'position' 

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#155]
I remember this to be the correct attrib name according to the IM.

**Comment by khaeru** [comment]
The Information Model states (page 55 / Section 5.3.1 / Figure 23) that the name is 'order'. 'position' does not appear anywhere in the IM.

In SDMX-ML messages (only), it is stored as an XML attribute named 'position', which might be what you remembered. `sdmxml.Reader.parse_dimension()` performs the translation: https://github.com/dr-leo/pandaSDMX/blob/c578985ac97ab358c3866de0763e2db6b580c327/pandasdmx/reader/sdmxml.py#L1095

(In SDMX-JSON messages, it is stored as a key named 'keyPosition'. This name also does not appear in the IM.)
