### ISSUE TITLE
Fix reversed dimension order in SeriesKey and DataMessage.structure

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#157]
We study ESTAT's une_rt_a dataflow from the 10-lines code example. We have queried the DSD named `dsd2`in the following code example. We have also queried a dataset. Now, an arbitrary serieskey from the DataMessage shows reverse dimension order compared to the DSD. The same reversed order is found in the DSD contained in the datamessage:

```

In [220]: sk.values
Out[220]:
DictLike([('UNIT', <KeyValue: UNIT=PC_ACT>),
          ('AGE', <KeyValue: AGE=TOTAL>),
          ('SEX', <KeyValue: SEX=F>),
          ('GEO', <KeyValue: GEO=DE>),
          ('FREQ', <KeyValue: FREQ=A>)])

In [221]: data_resp.structure.dimensions
Out[221]: <DimensionDescriptor: <Dimension: TIME_PERIOD>; <Dimension: UNIT>; <Dimension: AGE>; <Dimension: SEX>; <Dimension: GEO>; <Dimension: FREQ>>

In [222]: dsd2.dimensions
Out[222]: <DimensionDescriptor: <Dimension: FREQ>; <Dimension: AGE>; <Dimension: UNIT>; <Dimension: SEX>; <Dimension: GEO>; <TimeDimension: TIME_PERIOD>>

In [223]: dsd2.id
Out[223]: 'DSD_une_rt_a'

In [224]: data_resp.structure.id
Out[224]: 'DSD_une_rt_a'
```
In

**Comment by khaeru** [comment]
This is a good catch—also seems quite easy to write a test for. I can follow up on this.

**Comment by dr-leo** [comment]
Thanks. Frankly, I can't remember how I did it in v0.9 and if I got it right. Not even sure if dim order can be derived from a dataset other than by querying the DSD.

Thanks. Admittedly, I cannot remember how I did it in v0.9 and if I did it right. - Don't even know how to derive the dim order from a dataset. Well, I think I took the first series key to extract the dim IDs assuming they are rendered by LXML in the order as prescribed by the DSD. But I am not sure if the order is arbitrary from an XML standard perspective. I hope not. The fact that the order is reverse rather than shuffled points to a defined order in the xml message.

**Comment by dr-leo** [comment]
As #163 has partially covered up the issue by deriving the dim order from an external DSD rather than from the DataMessage itself, this issue is re-opened. Reversed dim order still occurs when there is no external DSD, notable in the following situations:

* a request for GenericData is made without a key or passing a str-typed key
* a GenericDataMessage is read from a file.
