### ISSUE TITLE
SDMX 1.0 support?

### ISSUE THREAD

**Issue by sflicht** [dr-leo/pandaSDMX#16]
Is it possible to add support for the 1.0 version of the standard used by the Federal Reserve Board? I assume this may be more involved than adding support for 2.0.

**Comment by dr-leo** [comment]
Hi,

apologies for the late Response. For some reason I don't receive E-Mail alerts on new issues.

It is certainly possible to either add an SDMX 1.0 Information model or a Reader that coerces SDMX1.0 XML files into the v2.1 model. That said, I won't do this in the foreseeable future unless someone pays me a fortune ;-)  

That said, there is a library called FREDAPI that might meet your Needs:

http://pandas.pydata.org/pandas-docs/stable/ecosystem.html

**Comment by dr-leo** [comment]
I consider this rather unrealistic for the forseeable future. A fork might be better to do this. Please reopen this issue if you would like to contribute code to this end.
