### ISSUE TITLE
Error message after import pandasdmx

### ISSUE THREAD

**Issue by Jacques2101** [dr-leo/pandaSDMX#178]
Hi I am using Pandasdmx (v 1.0.1 ) and I Have this message after : 
`import pandasdmx
`

/Users/jacques/opt/anaconda3/envs/Data/lib/python3.7/site-packages/pandasdmx/remote.py:11: RuntimeWarning: optional dependency requests_cache is not installed; cache options to Session() have no effect
  'to Session() have no effect', RuntimeWarning)

After that I cannot download data from Pandasdmx 

Thanks for your help

**Comment by dr-leo** [comment]
Hi,

The warning is a feature. Avoid it by installing requests-cache.

Please provide a Code example with traceback to help understand the
cause of the Problem.

Leo

**Comment by dr-leo** [comment]
I intend to release v1.1 soon. Is there still anything to be fixed or can this be closed? - Admittedly I haven't personally run any test without requests-cache installed...

**Comment by dr-leo** [comment]
This seems to be stale. Re-open if there is any bug.

**Comment by HEHenson** [comment]
Hi,
I had the same issue and pip3 install requests-cache fixed it just fine.
