### ISSUE TITLE
Add UNICEF SDMX data warehouse

### ISSUE THREAD

**Issue by yjaques** [dr-leo/pandaSDMX#180]
Would you consider adding UNICEF's indicator data warehouse on the state of women and children to your default provider list? https://sdmx.data.unicef.org
Note we are also members of the SDMX TWG, and SIS-CC community members, so reasonably active in the SDMX space.

**Comment by dr-leo** [comment]
Sure. Will do this asap and make a new release. Will also remove
UNESCO as they have terminated their SDMX Service.

**Comment by dr-leo** [comment]
See first implementation in #182 to be merged and relased soon.

**Comment by yjaques** [comment]
URL looks good, thanks for following up! Will be webinaring this in the near future for internal power users here that use Python to do their analytics, look forward to the release.

**Comment by dr-leo** [comment]
Closing this as v1.1.0 has been released. I haven't done much testing. I noted though that the COVID dataset contains non-numeric indicator values such as "<1". Hence, when exporting to pandas, the default dtype NP.float64 causes ValueError. Set dtype to str to avoid this. 

Please let me know of any further hiccups regarding UNICEF data.

**Comment by yjaques** [comment]
Thanks much appreciated. Yes, we have several datasets that have non-numeric values or ranges. In fact that was a deciding factor in having to move off of the EuroSTAT RI web services as they do not support alphanumeric observation values (although I note that the SDMX 2.0 COG specifically lists OBS_VAL as alphanumeric representation: https://sdmx.org/wp-content/uploads/SDMX_Glossary_Version_2_0_October_2018.htm#_Toc529282210)

I don't think you will find anything else out of the ordinary. Look forward to using the library now and plan to do an internal webinar in the next months!
