### ISSUE TITLE
HTTPError when requesting INSEE dataflow

### ISSUE THREAD

**Issue by bertrandmarc** [dr-leo/pandaSDMX#192]
Dear developper,

I get a HTTPError when requesting INSEE dataflow.
```python
import pandasdmx as sdmx
insee  = sdmx.Request('INSEE')
insee.dataflow()
```
results in
```python
>>> insee.dataflow()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bbk/.local/lib/python3.8/site-packages/pandasdmx/api.py", line 420, in get
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://www.bdm.insee.fr/series/sdmx/dataflow/INSEE/latest
```
However, please note that INSEE does support the dataflow request, at the following addresses:
[https://www.bdm.insee.fr/series/sdmx/dataflow/ALL/latest](https://www.bdm.insee.fr/series/sdmx/dataflow/ALL/latest)
[https://www.bdm.insee.fr/series/sdmx/dataflow/FR1/latest](https://www.bdm.insee.fr/series/sdmx/dataflow/FR1/latest)

I guess a hook similar to ISTAT's would fix it, but not sure how.

Cheers,
Bertrand

**Comment by dr-leo** [comment]
Hi,

have you tried increasing the timeout? - Folks tend to binge-watch
Netflix these days...

If this doesn't help, INSEE may have changed their API in which case a
code change could be needed.

**Comment by dr-leo** [comment]
This should be fixed. I thought this was due to a server downtime. Please re-open is problems persist.
