### ISSUE TITLE
DataStructureDefinition from an XML file

### ISSUE THREAD

**Issue by brockfanning** [dr-leo/pandaSDMX#193]
I suspect this is another case where I using this library in an unexpected way, but wanted to get some feedback from the experts:

I have got a DSD as an XML file, and I would like to create a [DataStructureDefinition](https://pandasdmx.readthedocs.io/en/latest/api.html#pandasdmx.model.DataStructureDefinition) object. I know that one way to do it is to parse the XML, iterate over the various parts to get the dimensions/attributes/etc, and then construct the DataStructureDefinition object in code. But before diving into that I thought I would ask if anyone knows of a shortcut for starting from an XML file.

**Comment by dr-leo** [comment]
Did you try the pandasdmx.read_sdmx() function? If yes, what precisely
is missing?

>>>from pandasdmx import read_sdmx
>>> msg = read_sdmx("myfile.xml")
>>>DSD = msg.structure.<DSD:_ID>

The above should do the trick. Or else inspect the msg obj and its
content with dir() etc.

**Comment by brockfanning** [comment]
@dr-leo Perfect, thank you! I was able to get the DSD with `DSD = msg.structure[0]`.
