### ISSUE TITLE
'list' object has no attribute 'series'

### ISSUE THREAD

**Issue by g3blv** [dr-leo/pandaSDMX#196]
I'm testing the following example [Download FX rates](https://www.pythonsherpa.com/static/files/html/ECB%20-%20Open%20Data.html#BONUS:-pandaSDMX)

It seems like `data` should be of type `pandasdmx.model.DataSet` but I get `<class 'list'>`.

```python
set(s.key.FREQ for s in data.series)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'list' object has no attribute 'series'
```

Reading the [documentation](https://pandasdmx.readthedocs.io/en/v1.0/api.html#pandasdmx.message.DataMessage.data) it looks like  `data_response.data` should return a [DataSet](https://pandasdmx.readthedocs.io/en/v1.0/api.html#pandasdmx.model.DataSet.series) that I should be able to turn into a `series`.

Have I missed something in my code?

**Full code**
```python
from pandasdmx import Request
ecb = Request('ECB')

data_response = ecb.data(resource_id = 'EXR', key={'CURRENCY': ['CHF', 'EUR']}, params = {'startPeriod': '2016'})
data = data_response.data

type(data)

set(s.key.FREQ for s in data.series)

daily = (s for s in data.series if s.key.FREQ == 'D')
ts2 = data_response.write(daily)
ts2.tail()
```
Running:
Python 3.8
pandaSDMX 1.2.0 from Conda Forge

**Comment by dr-leo** [comment]
DataMessage.data is a list of Dataset instances. So what you describe is a feature, not a bug. In v0.9, this was different. But the sdmxml specs allow multiple datasets in a single message, although I have never encountered this.

Please re-open if needed.
