### ISSUE TITLE
Error with some EUROSTAT flows if params['references'] is "all"

### ISSUE THREAD

**Issue by toobaz** [dr-leo/pandaSDMX#20]
If I run the following:

    from pandasdmx import Request

    key_args = {"UNIT"    : "CP_MEUR",
                "NA_ITEM" : "P51G"   ,
                "ASSET10" : "N1G"    ,
                "NACE_R2" : "A"      }

    req = Request('ESTAT')
    resp = req.get(resource_type="data", resource_id="nama_10_a64_p5", key=key_args)

I get the following:

    ---------------------------------------------------------------------------
    HTTPError                                 Traceback (most recent call last)
    <ipython-input-2-2d64bff3dfb5> in <module>()
          5 
          6 req = Request('ESTAT')
    ----> 7 resp = req.get(resource_type="data", resource_id="nama_10_a64_p5", key=key_args)

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/api.pyc in get(self, resource_type, resource_id, agency, key, params, fromfile, tofile, url, get_footer_url, memcache)
        219         # Now get the SDMX message either via http or as local file
        220         source, url, headers, status_code = self.client.get(
    --> 221             base_url, params=params, fromfile=fromfile)
        222         # write msg to file and unzip it as required, then parse it
        223         with source:

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/remote.py in get(self, url, fromfile, params)
         80         else:
         81             source, final_url, headers, status_code = self.request(
    ---> 82                 url, params=params)
         83         return source, final_url, headers, status_code
         84 

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/remote.py in request(self, url, params)
        104             code = int(response.status_code)
        105             if 400 <= code <= 499:
    --> 106                 raise response.raise_for_status()
        107             return source, response.url, response.headers, code

    /usr/lib/python2.7/dist-packages/requests/models.pyc in raise_for_status(self)
        849 
        850         if http_error_msg:
    --> 851             raise HTTPError(http_error_msg, response=self)
        852 
        853     def close(self):

    HTTPError: 400 Client Error: Bad Request

This doesn't happen with *all* Request.get() (e.g. I never had this problem with ECB data so far).

The problem is "solved" if in remote.py, at the beginning of the definition of REST.request(), I add the lines:

            if 'references' in params:
                del params['references']

To be honest, I have no idea of what this means, but I didn't notice any side effect.

**Comment by dr-leo** [comment]
Looks like a feature/bug of Eurostat. Server limits?

The del statement in remote.py breaks other stuff.

Clean solution: 

Pass `'references': None`

to the params arg as shown on the docs homepage with 'startPeriod'. This overrides the default value 'all'.

**Comment by toobaz** [comment]
OK, thanks
