### ISSUE TITLE
Unable to override default data source

### ISSUE THREAD

**Issue by equizole** [dr-leo/pandaSDMX#201]
Hi dr-leo,

Thanks for your work on this package!

I'm a novice Python user so hopefully I'm not causing you any unnecessary leg work but I think I spotted a bug in the `add_source()` method.  There is an `override` parameter for this function but it doesn't appear to be referenced in the function itself so you effectively are unable to override any of the default data sources.

Thanks for your attention.

**Comment by dr-leo** [comment]
Thanks for spotting this. It is a bug. Will fix this asap. Meanwhile,
you may work around it by choosing a unique data source ID such as
"ECB2" instead of "ECB"?

**Comment by equizole** [comment]
That's the workaround we've used.  Thanks for your quick response!
