### ISSUE TITLE
Find all value available for a key

### ISSUE THREAD

**Issue by fcarpentey75012** [dr-leo/pandaSDMX#202]
Hello, 

I would like to know, if it's possible to have the value available for a keys. 

In the documentation I can find this information : 
`key = dict(CURRENCY=['USD', 'JPY'])`

But, I would like to know what is the value of keys is available, because when I try to run this script 
`params = dict(startPeriod='2018',)
key = dict(CURRENCY=['USD','JPY'], FREQ=['A'],EXR_SUFFIX=['T'] )
ecb = sdmx.Request('ECB',proxies=proxyDict)
data_msg = ecb.data('EXR', key=key)
data = data_msg.data[0]`

I have an Error 404 Client Error,

Do you have some idea ? 

Thank you

**Comment by dr-leo** [comment]
Try upgrading to pandasdmx 1.4.0.

**Comment by dr-leo** [comment]
Apolgoies for the very late response.

An explample of how to retrieve the values allowed for a particular dimension which forms part of a key can be found at

https://pandasdmx.readthedocs.io/en/v1.0/example.html

Note that v1.4.x does not fully support content constraints. Therefore, you might see values in the code-lists for some dimensions which do not produce actual data, e.g., an exotic currency.

You can  modify the code for ECB exchange rates in a similar fashion. Pls let me know if this works for you. If so, pls close this issue.

**Comment by dr-leo** [comment]
If problem persists, upgrade to v1.8.0, released today, then reopen this isue.
