### ISSUE TITLE
XML Parse Error on Annotation in DSD

### ISSUE THREAD

**Issue by yjaques** [dr-leo/pandaSDMX#205]
When parsing a DSD with annotations returns an error:

XMLParseError: AssertionError: {'annotations': Annotation(id=None, title='HCL', type='urn:sdmx:org.sdmx.infomodel.codelist.Hierarchy=UNICEF:REGIONS_HIERARCHY(1.0).UNICEF_REG_1', url=None, text=)}

Stack:
Structure
> Structures
> DataStructures
> DataStructure
> DataStructureComponents
> DimensionList

<str:Dimension xmlns:str="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:com="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" urn="urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=UNICEF:DSD_NUTRITION(1.0).REF_AREA" id="REF_AREA" position="1">
  <com:Annotations>
    <com:Annotation>
      <com:AnnotationTitle>HCL</com:AnnotationTitle>
      <com:AnnotationType>urn:sdmx:org.sdmx.infomodel.codelist.Hierarchy=UNICEF:REGIONS_HIERARCHY(1.0).UNICEF_REG_1</com:AnnotationType>
    </com:Annotation>
  </com:Annotations>
  <str:ConceptIdentity>
    <Ref maintainableParentID="UNICEF_CONCEPTS" package="conceptscheme" maintainableParentVersion="1.0" agencyID="UNICEF" id="COUNTRY" class="Concept"/>
  </str:ConceptIdentity>
  <str:LocalRepresentation>
    <str:Enumeration>
      <Ref package="codelist" agencyID="UNICEF" id="CL_COUNTRY" version="1.0" class="Codelist"/>
    </str:Enumeration>
  </str:LocalRepresentation>
</str:Dimension>

**Comment by dr-leo** [comment]
Hi,
Thanks for raising this. Could you please send the code which produces the error? Alternative, you could send the XML file.

**Comment by yjaques** [comment]
Sure, the code is very simple:

`
req = sdmx.Request('UNICEF')
req.datastructure('DSD_NUTRITION')
`
However I removed the annotation so that it no longer breaks. Artifact was non-final so not a problem there, but it would be good to support this. Let me know if you need me to try and recreate that structure, but I think you can see in the error message,  it was a dimension level annotation.

**Comment by dr-leo** [comment]
Pls report if error persists with pandasdmx v1.8.0
