### ISSUE TITLE
XML Parse Error in Dataflow with data provider scheme

### ISSUE THREAD

**Issue by yjaques** [dr-leo/pandaSDMX#206]
XML Parser has no reader for data provider scheme and returns error:

XMLParseError: AttributeError: 'Reader' object has no attribute 'parse_dataproviderscheme'

Stack:
Structure
> Structures
> OrganisationSchemes

<str:DataProviderScheme xmlns:str="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:com="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" urn="urn:sdmx:org.sdmx.infomodel.base.DataProviderScheme=UNICEF:DATA_PROVIDERS(1.0)" isExternalReference="false" agencyID="UNICEF" id="DATA_PROVIDERS" isFinal="false" version="1.0">
  <com:Name xml:lang="it">DATA_PROVIDERS</com:Name>
  <str:DataProvider urn="urn:sdmx:org.sdmx.infomodel.base.DataProvider=UNICEF:DATA_PROVIDERS(1.0).UNICEF" id="UNICEF">
    <com:Name xml:lang="en">UNICEF Official Data</com:Name>
  </str:DataProvider>
  <str:DataProvider urn="urn:sdmx:org.sdmx.infomodel.base.DataProvider=UNICEF:DATA_PROVIDERS(1.0).UNICEF_DRAFT" id="UNICEF_DRAFT">
    <com:Name xml:lang="en">UNICEF Draft Data</com:Name>
  </str:DataProvider>
</str:DataProviderScheme>

**Comment by yjaques** [comment]
What I had to do to make this call work was to scope the references, like:

`req = sdmx.Request('UNICEF')`
`req.dataflow('NUTRITION',params={'references': 'Descendants'})`

So that it does not get the "siblings" such as data providers.

However this seems to create another challenge, not sure if it is related to using references, but my dataflow does not seem to be the right kind of object when I try to start accessing the descendants like "structure", they are dictionary-like objects, and I can't dig further into the attributes like, dsd.dimensions.components. Am I just missing a step?

**Comment by dr-leo** [comment]
You have the right intuition. Use the structure attribute of the
dataflow definition to obtain the ID of the datastructure definition
(DSD). Then do something like:

DSD_msg = Request('unicef').datastructure(DSD_id)

**Comment by dr-leo** [comment]
Probably solved in v1.8.0. Pls reopen if needed.
