### ISSUE TITLE
to_pandas cannot process non-numeric values

### ISSUE THREAD

**Issue by yjaques** [dr-leo/pandaSDMX#211]
When pulling a dataset with non-numeric values following error was reported:

`ValueError: could not convert string to float: 'Yes'`

To reproduce:
```
sdmx.writer.DEFAULT_RTYPE = 'rows'
req = sdmx.Request('UNICEF')
dataflowName = 'GLOBAL_DATAFLOW'
dataFlow = req.dataflow(dataflowName)
dataStructure = list(dataFlow.structure.values())[0]
key = dict(REF_AREA=['IND','DZA','BFA'])
params = dict(startPeriod='1980')
data = req.data(dataflowName, key=key, params=params,dsd=dataStructure)
data.to_pandas()
```

**Comment by dr-leo** [comment]
I am glad you've raised this.

In fact, the writer can create dataframes with non-numeric values, but the dtype defaults to numpy.float64. So you have to provide a suitable dtype manually. While I cannot reproduce this as I only work with numeric data so far, I recommend to try something like:

df = data_msg.to_pandas(dtype=numpy.String[20]) # or whatever suits the measure type defined by the DSD.

I want a mechanism that derives and sets a suitable dtype given the facets defined in the DSD if the user provides the DSD to the writer, resp. the to_pandas().

Please let me know if this helps.

**Comment by yjaques** [comment]
Yes that worked, thanks! Theoretically, one could define the OBS_VALUE data type in the concept scheme using <str:CoreRepresentation>

**Comment by dr-leo** [comment]
Could you pls provide one or two code examples / dataflows with non-numerical values? This would help work on a more intelligent type selection mechanism.

**Comment by jamescw** [comment]
Hi @dr-leo,

I am a colleague of @yjaques working in our Geneva office and let me firstly thank you for this library it is really useful for our python data apps!

Here is how you can reproduce this error:

```
unicef = sdmx.Request("UNICEF")

metadata = unicef.dataflow("TRANSMONEE", provider="ECARO", version="1.0")

dsd = metadata.structure['DSD_ECARO_TRANSMONEE']

message = unicef.data(
    "TRANSMONEE", 
    provider="ECARO", 
    key={
        'INDICATOR': ['EDUNF_ADMIN_L2_MAT'],
        'SEX': ['_T'],
        'RESIDENCE': ['_T'],
        'WEALTH_QUINTILE': ['_T']
    }, 
    params = dict(startPeriod='2010', endPeriod='2021', lastNObservations=1), 
    dsd=dsd
)

df = message.to_pandas(attributes="o", rtype="rows")
```
However as you mention above it is straight forward to get around currently with:

    df = message.to_pandas(attributes="o", rtype="rows", dtype="str")

Hope this helps,
James

**Comment by dr-leo** [comment]
Thanks. v1.10.0 will allow dtypes to be derived from the DSD. P.ex., enumerated values (mostly for attributes) will be represented as categorical columns.

See #228.
