### ISSUE TITLE
How to set attributes in pandasdmx

### ISSUE THREAD

**Issue by quant12345** [dr-leo/pandaSDMX#212]
I can pass the dimensions, but I can't set the attributes.
Show an example of how to set attributes?
```
import pandasdmx as sdmx
import pandas as pd

ecb = sdmx.Request('ECB')
key = dict(FREQ=['M'], SEC_ITEM=['F51100'], REF_AREA = ['I8'], SEC_ISSUING_SECTOR = ['1000'])
params = dict(startPeriod='2010-02', endPeriod='2010-02')
data_msg = ecb.data('SEC', key=key, params=params)

flow_msg = ecb.dataflow()
dataflows = sdmx.to_pandas(flow_msg.dataflow)
exr_msg = ecb.dataflow('SEC')
exr_flow = exr_msg.dataflow.SEC
dsd = exr_flow.structure

dimen = dsd.dimensions.components
attrib = dsd.attributes.components
print(dimen)
print(attrib)
```

**Comment by dr-leo** [comment]
I understand your question as follows:

Is it possible to query data such that the server will return only observations whose attributes take on specific values? - In other words: Can one filter not just by dimension values, but also by attribute value?

If this is your question, the answer is: no.

You could do this in an SQL query. But the SDMX 2.1 REST API does not support such queries.

As a workaround you may query a dataset specified by some key (= dimension values), export it as a pandas DataFrame containing both observation values and attributes (pass the rtype param to the to_pandas method), and filter rows for the desired attribute values using pandas features.

**Comment by quant12345** [comment]
In the Fed statistics, there is the first and last value(the second is when the revision occurs).
Is there such a thing in ECB?

**Comment by dr-leo** [comment]
I don't know anything about Fed stats. Past research suggests Fed does 
not support SDMX 2.1, at least it has no web API. Any updates?


So I do not understand your question.


Yet, a few comments:


1. The SDMX REST API specs support a `version` URL part which is set to 
'latest' by default. Find out on the ECB web site what other values are 
allowed and play with it.

2. Look at the params supported by the ECB web API. There may be more to 
discover besides startPeriod and endPeriod. Maybe even a historic 
snapshot of the data.

3. You may find hints in the SDMX web services guidelines at 
www.sdmx.org. They describe points 1 and 2 above, and more.

4. SDMX 2.1 has been extended to include a transformation language. 
While pandasdmx does not support this feature yet, nor am I aware 
whether any data sources do, it may be worthwhile looking at this in the 
long run. But I don't even know if this is related to your question.


Keep me in the loop, including on Fed stats, if Fed now has an SDMX API etc.



Am 28.05.2021 um 22:21 schrieb quant12345:

**Comment by quant12345** [comment]
Thank you, I'll try to learn the ECB web API.
I took the statistics on the Fed from [FRED](https://fred.stlouisfed.org/docs/api/fred/#Toolkits)
there are links to the implementation in Python.
On the Fed website when selecting data to download: 
"Download all H3 data as a single XML file [SDMX/ZIP, 500.1 [KB]"](https://www.federalreserve.gov/datadownload/Choose.aspx?rel=H3)
Although I'm not sure if this is the SDMX format.
To be honest I don't understand SDMX very well)

The statistics on the Fed were given as an example.
Suggested that in ECB might be something similar to what I'm looking for.
A couple of weeks ago, I didn't even know there was an SDMX data format.

**Comment by dr-leo** [comment]
This seems to be solved. Pls reopen if problem persists.
