### ISSUE TITLE
Find the URL after the request

### ISSUE THREAD

**Issue by fcarpentey75012** [dr-leo/pandaSDMX#213]
Hello, 

I would like to know if it's possible after have to use sdmx.Request() to retrieve the URL use by pandas to request the data provider ? 
Like response.url ? 

Thank you,

**Comment by dr-leo** [comment]
Not sure if I get your question. But try something like:

```
msg = Request('ECB').dataflow()
msg.response.url
```

This works for all requests.

**Comment by fcarpentey75012** [comment]
Hello, yes perfect thank you
