### ISSUE TITLE
Error mix string/float

### ISSUE THREAD

**Issue by fcarpentey75012** [dr-leo/pandaSDMX#214]
Hello, 

For twos dataprovider UNICEF and CD2030 we have this data 

ValueError: could not convert string to float: '<1'
or 

ValueError: could not convert string to float: 'Yes'

After to check this error, I see the key "Value" has been define by numpy.float64 by default. Maybe we can add in pandasdmx.writer.pandas line 313 just a control to be sure if the value is a numeric value. Because in this case we have its example of value 

<1
1.3
<1
2.8
4.2

We have a mix between numeric value and string value. And for UNICEF we have Yes or No value. 

Thank you,
Florian

**Comment by dr-leo** [comment]
Same as #211. Pass a suitable dtype such as 'object' or maybe 'str' or numpy.Str[30] if it exists and pandas supports it. The default, np.float64 does not work for "<1". The fix you suggest would be ad-hoc-ish and lack generality.

You want to parse yes/no as bool. Check if pandas can do this with 'bool' or something.

In the worst case, set dtype to 'object', then massage the dataframe to your liking, eg. setting "<1" to n/a, 0.999999 or whatever, then convert to float. 

I am afraid there's no clean solution.
