### ISSUE TITLE
Parsing XML structure from OECD (SDMX-ML API)

### ISSUE THREAD

**Issue by beto-Sibileau** [dr-leo/pandaSDMX#215]
Hi @dr-leo! I've seen, OECD only reports datastructures through their SDMX-ML API (whereas data can be retrieved from both SDMX-ML and SDMX-JSON APIs).

The pandasdmx reader fails when attemping to read datastructure from SDMX-ML API (e.g: [CWB_dsd.txt](https://github.com/dr-leo/pandaSDMX/files/6733576/CWB_dsd.txt) file attached) with the following issue: `Unrecognized message root element '{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}Structure'`:

```
import pandasdmx as pdsdmx
import requests
api_address = 'https://stats.oecd.org/restsdmx/sdmx.ashx/GetDataStructure/CWB'
response = requests.get(api_address)
dsd_file = 'CWB_dsd.xml'
with open(dsd_file, "wb") as f:
    f.write(response.content)
xml_message = pdsdmx.read_sdmx(dsd_file)
```
Seems to me the latter structural metadata query reports *XML Schema Structure* format and not any of the [formats here reported](https://github.com/sdmx-twg/sdmx-rest/blob/master/v2_1/ws/rest/docs/4_6_conneg.md).

Any thoughts on how source code could be modified to incorporate this *XML Schema Structure* into pandasdmx reader?

**Comment by dr-leo** [comment]
This is a documented feature for OECD, only data messages in JSON format our support it. The structure message you are trying to Paris is in DMXML 2.0 format. However, the library only supports sdmxjson ML 2.1. I am afraid there is no workaround. However, please note that data messages in JSON format contain a lot of structural meta-data. So the data message should contain this structural information.As a data structure definition. In practice, you may wish to look at the see as a data structure definition. In practice, you may wish to look at the OECD website to find out about available data flows.

**Comment by beto-Sibileau** [comment]
thank you for your support @dr-leo
