### ISSUE TITLE
datastructure() and codelist() functions raise  XMLParseError in Bundesbank (BBK) Source 

### ISSUE THREAD

**Issue by ngalanin** [dr-leo/pandaSDMX#217]
Hello, I am not sure why but the datastructure() and codelist() functions raise  XMLParseError when i use Bundesbank (BBK) as a source. An the dsd.components.components have empty values. The code is attached as a screenshot. Am I doing something wrong and missing some parameters? Or is something wrong with the XML? Thank you in advance! 

![Code](https://user-images.githubusercontent.com/58103657/129452876-cbb76be3-414d-4f57-a103-7e09b42db13b.png)

**Here is the Error Message in datastructure() function:**

--- SS without DSD ---
[False]

--- <class 'pandasdmx.message.StructureMessage'> ---
[<pandasdmx.StructureMessage>
  <Header>
    id: 'IREF1628957005970'
    prepared: '2021-08-14T18:03:25.970000+02:00'
    receiver: <Agency not_supplied>
    sender: <Agency BBK>
    source: 
    test: False]

--- <class 'pandasdmx.model.DataStructureDefinition'> ---
[<DataStructureDefinition BBK:BBK_ACIP(1.0)>]

--- Name ---
[('en', 'Deutsche Bundesbank,  Insurance Corporations and Pension Undertakings Statistics'), ('de', 'Deutsche Bundesbank, Statistik der Versicherungen und  Pensionseinrichtungen')]

--- <class 'pandasdmx.model.Codelist'> ---
[<Codelist BBK:CL_BBK_STD_FREQ(1.0) (0 items)>, <Codelist BBK:CL_BBK_STD_AREA(1.0) (0 items)>, <Codelist BBK:CL_BBK_STD_ADJUSTMENT(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_VALUATION(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_DATA_TYPE(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_INSTRUMENT(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_REF_SEC(1.0) (0 items)>, <Codelist BBK:CL_BBK_STD_AREA(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_COUNT_SEC(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_ASSET_LIABILITY(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_CONSOLIDATION(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_DENOMINATION(1.0) (0 items)>, <Codelist BBK:CL_BBK_ACIP_SUFFIX(1.0) (0 items)>]

--- <class 'pandasdmx.model.ConceptScheme'> ---
[<ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>, <ConceptScheme BBK:CS_BBK_ACIP(1.0) (1 items)>]

<structure:DimensionList xmlns:structure="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" id="DimensionDescriptor" urn="urn:sdmx:org.sdmx.infomodel.datastructure.DimensionDescriptor=BBK:BBK_ACIP(1.0).BBK_ACIP">
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:Dimension/>
  <structure:TimeDimension/>
</structure:DimensionList>

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in read_message(self, source, dsd)
    247                     # Parse the element
--> 248                     result = func(self, element)
    249                     self.push(result)

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in _cl(reader, elem)
    912 
--> 913     cl = reader.identifiable(cls, elem, **args)
    914 

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in identifiable(self, cls, elem, **kwargs)
    431         setdefault_attrib(kwargs, elem, "id", "urn", "uri")
--> 432         return self.annotable(cls, elem, **kwargs)
    433 

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in annotable(self, cls, elem, **kwargs)
    426             kwargs["annotations"].extend(self.pop_all(model.Annotation))
--> 427         return cls(**kwargs)
    428 

~\anaconda3\lib\site-packages\pandasdmx\model.py in __init__(self, *args, **kwargs)
    241             if self.id not in (self.urn_group["item_id"] or self.urn_group["id"]):
--> 242                 raise ValueError(f"ID {self.id} does not match URN {self.urn}")
    243         except KeyError:

ValueError: ID DimensionDescriptor does not match URN urn:sdmx:org.sdmx.infomodel.datastructure.DimensionDescriptor=BBK:BBK_ACIP(1.0).BBK_ACIP

The above exception was the direct cause of the following exception:

XMLParseError                             Traceback (most recent call last)
<ipython-input-190-8c3cbb3fe4b4> in <module>
----> 1 meta=bb.datastructure()

~\anaconda3\lib\site-packages\pandasdmx\api.py in get(self, resource_type, resource_id, tofile, use_cache, dry_run, **kwargs)
    474 
    475         # Parse the message, using any provided or auto-queried DSD
--> 476         msg = reader.read_message(response_content, dsd=kwargs.get("dsd", None))
    477 
    478         # Store the HTTP response with the message

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in read_message(self, source, dsd)
    256             self._dump()
    257             print(etree.tostring(element, pretty_print=True).decode())
--> 258             raise XMLParseError from exc
    259 
    260         # Parsing complete

XMLParseError: ValueError: ID DimensionDescriptor does not match URN urn:sdmx:org.sdmx.infomodel.datastructure.DimensionDescriptor=BBK:BBK_ACIP(1.0).BBK_ACIP

**Here is the Error Message in codelist() function:**
![code2](https://user-images.githubusercontent.com/58103657/129452929-6989b1b4-617a-4434-a68b-7fa3d2c89cf1.png)

--- SS without DSD ---
[False]

--- <class 'pandasdmx.message.StructureMessage'> ---
[<pandasdmx.StructureMessage>
  <Header>
    id: 'IREF1628957531488'
    prepared: '2021-08-14T18:12:11.488000+02:00'
    receiver: <Agency not_supplied>
    sender: <Agency BBK>
    source: 
    test: False]

--- Name ---
[('en', 'Collection indicator code list (BBk)'), ('de', 'Erlaubte Angaben für die Umrechnungsart')]

<structure:Codelist xmlns:structure="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" xmlns:common="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common" agencyID="BBK" isFinal="false" isExternalReference="false" version="1.0" id="CLA_BBK_COLLECTION" urn="urn:sdmx:org.sdmx.infomodel.codelist=BBK:CLA_BBK_COLLECTION(1.0)">
  <common:Name/>
  <common:Name/>
</structure:Codelist>

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in read_message(self, source, dsd)
    247                     # Parse the element
--> 248                     result = func(self, element)
    249                     self.push(result)

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in _itemscheme(reader, elem)
    801 
--> 802     return reader.maintainable(cls, elem, items=items)
    803 

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in maintainable(self, cls, elem, **kwargs)
    467         # Create a candidate object
--> 468         obj = self.nameable(cls, elem, **kwargs)
    469 

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in nameable(self, cls, elem, **kwargs)
    439         """
--> 440         obj = self.identifiable(cls, elem, **kwargs)
    441         if elem is not None:

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in identifiable(self, cls, elem, **kwargs)
    431         setdefault_attrib(kwargs, elem, "id", "urn", "uri")
--> 432         return self.annotable(cls, elem, **kwargs)
    433 

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in annotable(self, cls, elem, **kwargs)
    426             kwargs["annotations"].extend(self.pop_all(model.Annotation))
--> 427         return cls(**kwargs)
    428 

~\anaconda3\lib\site-packages\pandasdmx\model.py in __init__(self, **kwargs)
    386     def __init__(self, **kwargs):
--> 387         super().__init__(**kwargs)
    388         try:

~\anaconda3\lib\site-packages\pandasdmx\model.py in __init__(self, **kwargs)
    336     def __init__(self, **kwargs):
--> 337         super().__init__(**kwargs)
    338         try:

~\anaconda3\lib\site-packages\pandasdmx\model.py in __init__(self, *args, **kwargs)
    237 
--> 238             self.urn_group = pandasdmx.urn.match(self.urn)
    239 

~\anaconda3\lib\site-packages\pandasdmx\urn.py in match(string)
     43 def match(string):
---> 44     return URN.match(string).groupdict()

AttributeError: 'NoneType' object has no attribute 'groupdict'

The above exception was the direct cause of the following exception:

XMLParseError                             Traceback (most recent call last)
<ipython-input-191-82cec0e84460> in <module>
----> 1 bb.codelist()

~\anaconda3\lib\site-packages\pandasdmx\api.py in get(self, resource_type, resource_id, tofile, use_cache, dry_run, **kwargs)
    474 
    475         # Parse the message, using any provided or auto-queried DSD
--> 476         msg = reader.read_message(response_content, dsd=kwargs.get("dsd", None))
    477 
    478         # Store the HTTP response with the message

~\anaconda3\lib\site-packages\pandasdmx\reader\sdmxml.py in read_message(self, source, dsd)
    256             self._dump()
    257             print(etree.tostring(element, pretty_print=True).decode())
--> 258             raise XMLParseError from exc
    259 
    260         # Parsing complete

XMLParseError: AttributeError: 'NoneType' object has no attribute 'groupdict'

**Comment by dr-leo** [comment]
That's weird. That said, a data source does not necessarily have to
support 'codelist'. 'datastructure' should yield clean xml though. To
support BBK, I had to change a couple of things besides the odd stuff
you've encountered.

As a first attempt to find a workaround, try a request for dataflow
specifying a dataflow ID:

flow_msg = Request('bbk').dataflow(<insert dataflow ID>)

This should give you the specified dataflow artefact with refereced
artefacts such as datastructure definition, codelists etc. without
explicitly querying a specified datastructure.

Please let me know if this works for you.

PS: The 10 lines code example in the docs should thus be simplified as well.

**Comment by dr-leo** [comment]
Fixed in v1.8.0.
