### ISSUE TITLE
Choose language

### ISSUE THREAD

**Issue by paulineml** [dr-leo/pandaSDMX#219]
Hi, 
I would like to be able to specify the output language 

```
req = sdmx.Request()
response = req.get(url=URL)
df = sdmx.to_pandas(response)
```
in the sdmx to pandas step (or elsewhere). 

Is this what you mean to implement in the documentation in your 
**Todo:
Support selection of language for conversion of InternationalString.** ?

From what I see, it would need to add the possibility to set locale to something else than DEFAULT_LOCALE in sdmx.to_pandas().

Would you be able to estimate when this will be done ?

It would be very helpful to me. Thank you very much, 

Pauline ML

**Comment by dr-leo** [comment]
Solved in #224. Request class has now a property `default_locale`. It is used by writers to extract str values. It is set to 'en' by default as before. Now you can easily change it from public API. 

This should be relased in a week or so.
