### ISSUE TITLE
AttributeError at import

### ISSUE THREAD

**Issue by toobaz** [dr-leo/pandaSDMX#22]
In branch v0.3.2dev, a simple

    from pandasdmx import Request

yields the following error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-86e12c071071> in <module>()
    ----> 1 from pandasdmx import Request

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/__init__.py in <module>()
         15 
         16 
    ---> 17 from pandasdmx.api import Request
         18 
         19 

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/api.py in <module>()
         20 from pandasdmx import remote
         21 from pandasdmx.utils import str_type
    ---> 22 from pandasdmx.reader.sdmxml import SDMXMLReader
         23 from importlib import import_module
         24 from zipfile import ZipFile, is_zipfile

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/reader/sdmxml.py in <module>()
         15 
         16 from pandasdmx.utils import DictLike, namedtuple_factory
    ---> 17 from pandasdmx import model
         18 from pandasdmx.reader import BaseReader
         19 from lxml import etree

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/model.py in <module>()
        654 
        655 
    --> 656 class StructureMessage(Message):
        657     _content_types = Message._content_types.copy()
        658     _content_types.extend([

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/model.py in StructureMessage()
        655 
        656 class StructureMessage(Message):
    --> 657     _content_types = Message._content_types.copy()
        658     _content_types.extend([
        659         ('codelists', 'read_identifiables', Codelist, None),

    AttributeError: 'list' object has no attribute 'copy'

**Comment by dr-leo** [comment]
This is a 2to3 problem. Need to fix this.

**Comment by dr-leo** [comment]
Thanks. Done.
