### ISSUE TITLE
Different language example and all languages possibility

### ISSUE THREAD

**Issue by paulineml** [dr-leo/pandaSDMX#229]
Hello, 

I am writing as a follow up for https://github.com/dr-leo/pandaSDMX/issues/219
Thank you for implementing the feature.

However, I can't find documentation or example explaining how to specify the output language.  Would you have an example ?

Also, there might be some use case where it would be useful to get all the languages as separate columns in the pandas dataframe. Is it an option here ?

Thank you very much

**Comment by dr-leo** [comment]
There is documentation in the walkthrough section under the heading
"Internationalization".

Exporting
a dataframe (of what?) with international strings within all kinds of SDMX
objects (Codes, DSDs, dimensions, concepts etc.) in all available languages
would require some more profound changes to the pandas writer. It is not
guaranteed that all international strings within a message or within a
codelist have the same set of languages etc. I don't have enough resources
to do this. But you could do a hack in a few lines by directly accessing
the information model, i.e. browsing the codelists within a structure
message.

>>> msg.codelist.CL_FREQ.A.name
