### ISSUE TITLE
AttributeError: 'Reader' object has no attribute 'footer_text'

### ISSUE THREAD

**Issue by toobaz** [dr-leo/pandaSDMX#24]
The following code:

    resp = Request('ESTAT').get("data", 'naio_10_pyp16', key={'FREQ': 'D', 'INDUSE': 'TOTAL'})

results in:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-3-477ab9e6fe65> in <module>()
    ----> 1 resp = Request('ESTAT').get("data", 'naio_10_pyp16', key={'FREQ': 'D', 'INDUSE': 'TOTAL'})

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/api.py in get(self, resource_type, resource_id, agency, key, params, fromfile, tofile, url, get_footer_url, memcache, writer)
        242             # Retrieve the first URL in the footer, if any
        243             url_l = [
    --> 244                 i for i in msg.footer.text if remote.requests.utils.urlparse(i).scheme]
        245             if url_l:
        246                 # found an URL. Wait and try to request it

    /home/pietro/nobackup/repo/pandaSDMX/pandasdmx/model.py in text(self)
         61     @property
         62     def text(self):
    ---> 63         return self._reader.footer_text(self)
         64 
         65     @property

    AttributeError: 'Reader' object has no attribute 'footer_text'

For the recors: before your commits of the last couple of weeks, the call still failed, but with a different error: an ``IndexError: list index out of range`` in ``writer/data2pandas.pyc`` in function ``write(self, source, asframe, dtype, attributes, reverse_obs, fromfreq, parse_time)``, at line ``level_names = list(index_source[0].name._fields)``

**Comment by toobaz** [comment]
Sorry, just a clarification: before your commits of the last couple of weeks, that call would *not* fail. But the subsequent ``res.write()`` would. The two problems are possibly unrelated.

**Comment by dr-leo** [comment]
Hi,
thanks for spotting this. It got lost when I refactored the writer.
I'll fix this hopefully next week.

On a separate note, I appreciate your contributions. Having looked at
your Website, I wonder if I could facilitate things by granting you
commit rights. We could briefly Exchange view on bigger ideas and you
could fix bugs independently.

Maybe you have noticed that I am working on a writer that will Export
structural metadata such as code list attributes (Name, description
etc.), datstructure-definitions, concept-schemes etc. to a PD
DataFrame. This is for the 0.4.0 release. And I think it is a nice
Feature as you can view code-lists in IPython Notebook etc.

The next big step would be to add a Reader for JSON to cover OECD and IMF data.

Please do not feel obliged to anything. But as I said, if commit
rights would be convenient for you, pls let me know.

Best,

Leo

**Comment by toobaz** [comment]
Il giorno mer, 25/11/2015 alle 10.36 -0800, dr-leo ha scritto:
> Hi,
> thanks for spotting this. It got lost when I refactored the writer.
> I'll fix this hopefully next week.
> 

Thanks!

> On a separate note, I appreciate your contributions. Having looked at
> your Website, I wonder if I could facilitate things by granting you
> commit rights. We could briefly Exchange view on bigger ideas and you
> could fix bugs independently.
> 

My understanding of the pandaSDMX code does not go very deep, and I'm
afraid I won't have much time to devote to the project... but sure, in
case I should spot other simple bugs like the one concerned by https://
github.com/dr-leo/pandaSDMX/pull/23 , I would gladly use commit rights
to just fix them.

> Maybe you have noticed that I am working on a writer that will Export
> structural metadata such as code list attributes (Name, description
> etc.), datstructure-definitions, concept-schemes etc. to a PD
> DataFrame. This is for the 0.4.0 release. And I think it is a nice
> Feature as you can view code-lists in IPython Notebook etc.
> 

Uhm... don't know how much of it can be interesting/related, but I
currently always work with a subclass of Request which fullfills some
needs I had. I will open a PR just now.

**Comment by dr-leo** [comment]
.
Btw: the above request returns the footer "no results found".
