### ISSUE TITLE
ECB rate querys stopped working from aprill

### ISSUE THREAD

**Issue by kadarpik** [dr-leo/pandaSDMX#243]
DEBUG:requests_cache.backends:Initializing backend: memory http_cache
DEBUG:requests_cache.policy.actions:Cache directives from request headers: {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sdw-wsrest.ecb.europa.eu:443
DEBUG:urllib3.connectionpool:https://sdw-wsrest.ecb.europa.eu:443 "GET /service/dataflow/ECB/EXR/latest?references=all HTTP/1.1" 404 None
DEBUG:requests_cache.session:Pre-cache checks for response from https://sdw-wsrest.ecb.europa.eu/service/dataflow/ECB/EXR/latest?references=all: {'disabled cache': False, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
DEBUG:requests_cache.session:Skipping cache write for URL: https://sdw-wsrest.ecb.europa.eu/service/dataflow/ECB/EXR/latest?references=all
currency query error

even simple test 

#!/usr/bin/env python3
import pandasdmx as sdmx

# Define the ECB data source
ecb = sdmx.Request('ECB')

# Fetch the latest exchange rates
data_response = ecb.data('EXR', {'CURRENCY': 'USD+JPY+GBP'}, key='ECB.M.D.USD.EUR.SP00.A', params={'startPeriod': 'latest'})

# Extract the exchange rates from the response
data = data_response.to_pandas()

# Print the exchange rates DataFrame
print(data)

returns the same error

**Comment by dr-leo** [comment]
The code example does not seem to be valid. Problem: It seems to pass two keys: one as positional arg, the other as HTML. - I have just downloaded EXR data from ECB without any problems. Please re-open when ready.
