### ISSUE TITLE
Warning while importing pandaSDMX

### ISSUE THREAD

**Issue by agnibhu13** [dr-leo/pandaSDMX#251]
import pandasdmx as sdmx

Warning (from warnings module):
  File "C:\Users\deepu\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandasdmx\remote.py", line 11
    warn(
RuntimeWarning: optional dependency requests_cache is not installed; cache options to Session() have no effect

**Comment by weltenseglr** [comment]
This is not an issue... It's up to you to install (and use) requests_cache
