### ISSUE TITLE
ObsKeyTuple error

### ISSUE THREAD

**Issue by srault95** [dr-leo/pandaSDMX#26]
Hi,

https://github.com/dr-leo/pandaSDMX/blob/master/pandasdmx/reader/sdmxml.py#L194

Replace ObsKeyTuple with self._ObsTuple ?

Thanks.

**Comment by dr-leo** [comment]
Hi,

pls include a traceback. Without it, I believe line 194 is correct.
First iteration raises NameError which is caught to generate the tuple
type in the except block. In further iterations Line 194 will succeed as
intended. Line 194 extracts the obs id, eg., the time period, or
whatever the dim_at_obs, of the observation.

Leo

Am 21.12.2015 um 15:52 schrieb Stéphane RAULT:

**Comment by dr-leo** [comment]
Reopen once you can describe the Problem.
