### ISSUE TITLE
ENH: semester and bi-monthly series

### ISSUE THREAD

**Issue by MichelJuillard** [dr-leo/pandaSDMX#29]
@dr-leo INSEE has some series on a semester basis (every 6 month) and on a bi-monthly basis (every 2 month)
pandas.Period() has no support for such frequencies. Do you see any workaround ?
Frequencies '6M' and '2M' don't see an option because then pandas.Period().ordinal increases by 6 (or 2) instead of 1, between adjacent periods. 
(I'm working with @srault95)

**Comment by dr-leo** [comment]
Hi,

great question. Pandas has some limitations in parsing datetime and
period strings. That said, in Pandas 0.17 there might be some Progress
in this respect.

The data2pandas writer attempts to do some pre-processing of These
strings to make them digestible for Pandas. But there are limitations.
I am sure the Pandas community welcomes any PRs in this area.

If you have any clear idea on how to improve on the pre-processing
code, please let me know or make a PR.

The only "Workaround" for now is to Switch off datetime parsing by
calling the 'write' method with 'parse_time=False', if I am not wrong.
In the resulting DataFrame you can then fiddle with the index as a
post-processing step.

Please let me know if any of the above works for you.

Leo

**Comment by dr-leo** [comment]
Hi,

I've rewritten the index Generation code. See the latest commit to master. If you send me the dataflow IDs of such 2M and 6M data sets or test the new Code, this would be much appreciated.

**Comment by dr-leo** [comment]
There has not been any Progress for a long time. 
I have added Support for semestrial data (FREQ='H') converting the FREQ tto '2Q". I might do this for bimonthly data as well, but I have no dataset to test, and not the time to search INSEE. - I do not see the Point why 2Q or 6M or indeed 2M would cause Problems iwth Pandas. When .ordinal jumps from 1 to 7 or 1,3,5 in case of bimonthly, where's the Problem? - Feel free to re-open if needed.
