### ISSUE TITLE
Custom header in get() function

### ISSUE THREAD

**Issue by srault95** [dr-leo/pandaSDMX#30]
Hi,

https://github.com/dr-leo/pandaSDMX/blob/master/pandasdmx/api.py#L244

This code is never called because it would have to be equal to None headers in the get () function

Thanks,

Stéphane.

**Comment by dr-leo** [comment]
Hi,

maybe this is a stupid question. But INSEE tends to return
structure-specific data-sets, although the headers do not necessarily
suggest this.. pandaSDMX cannot handle these, yet.


Any idea how to get generic datasets? Ensure the data set is small? -
The accept headers should not be the reason...

Leo

Am 28.12.2015 um 11:37 schrieb Stéphane RAULT:

**Comment by dr-leo** [comment]
Yet another question: Does passing empty or non-empty headers to the
underlying http lib 'requests' prevent it from Setting sensible
Default headers such as on accepting zipped Responses?

**Comment by srault95** [comment]
Hi,

1) For genericdata vs StructureSpecificData, yes, StructureSpecificData format is small and SDMX Json 2.1 is even smaller :)

I do not find what it lacks in PandasDMX to manage StructureSpecificData ?

2) For headers, no problem, see headers:
```
>>> from pprint import pprint
>>> from pandasdmx import Request
>>> insee = Request("INSEE")
>>> data = insee.get(resource_type="data", resource_id='CNA-2010-CONSO-SI-A17', headers=None)
>>> data.url
'http://www.bdm.insee.fr/series/sdmx/data/CNA-2010-CONSO-SI-A17'
>>> pprint(dict(data.http_headers))
{'Content-Encoding': 'gzip',
 'Content-Type': 'application/vnd.sdmx.genericdata+xml; version=2.1',
 'Date': 'Tue, 29 Dec 2015 10:09:21 GMT',
 'Server': 'INSEE',
 'Transfer-Encoding': 'chunked',
 'X-Frame-Options': 'DENY'}
```

Stéphane.
