### ISSUE TITLE
Error raised by the Example from documentation

### ISSUE THREAD

**Issue by MartinHa** [dr-leo/pandaSDMX#31]
Running the Example from the library documentation raises following error:

Traceback (most recent call last):
  File "/home/martin/NetBeansProjects/NewPythonProject/newpythonproject/newpythonproject.py", line 7, in <module>
    une_df = une_resp.write(s for s in une_resp.msg.data.series if s.key.AGE == 'TOTAL')
  File "/usr/local/lib/python3.4/dist-packages/pandasdmx/api.py", line 392, in write
    return self._writer.write(source=source, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pandasdmx/writer/data2pandas.py", line 127, in write
    d_frame = PD.concat(list(pd_series), axis=1, copy=False)
TypeError: concat() got an unexpected keyword argument 'copy'

After fixing the file /usr/local/lib/python3.4/dist-packages/pandasdmx/writer/data2pandas.py it seems to work.

**Comment by dr-leo** [comment]
Which pandas version are you using?

 




Am 09.03.2016 um 11:20 schrieb MartinHa:

**Comment by MartinHa** [comment]
ipdb> import pandas as pd
ipdb> pd.__version__
'0.13.1'

**Comment by dr-leo** [comment]
This version is incompatible. Upgrade to 0.17 and things will work.


Am 09.03.2016 um 14:48 schrieb MartinHa:

**Comment by dr-leo** [comment]
Closed.


Am 09.03.2016 um 14:48 schrieb MartinHa:

**Comment by MartinHa** [comment]
ipdb> import pandas as pd
ipdb> pd.__version__
'0.13.1'

it is implic version for Ubuntu 14.04LTS

**Comment by dr-leo** [comment]
I recommend using Anaconda python distribution as stated in the docs.
pandas 0.13 is outdated.

Am 09.03.2016 um 14:50 schrieb MartinHa:

**Comment by MartinHa** [comment]
OK, thanks
Martin
