### ISSUE TITLE
Add ISTAT as data provider

### ISSUE THREAD

**Issue by esvhd** [dr-leo/pandaSDMX#32]
Hi,

I just read the docs and there is an example to select data from a particular agency. I wonder if there is a feature that allows us to point to a particular SDMX url link and read the file directly? Example, Banca d'Italia webiste: 
https://a2a.bancaditalia.it/infostat/dataservices/export/EN/SDMXv21/DATA/CUBE/BANKITALIA/DIFF/FSI

This is from: http://www.istat.it/nsdp/

I saved the file to my local disk. I read the docs online but the section on that is quite limited. All I managed to do is the following. Not sure what else I need to do to convert data into a `pandas.DataFrame`... Any ideas? Would be great if the docs had a full example of how reading from a file worked.

``` python
import pandasdmx as sdmx
req = sdmx.Request()
res = req.get(fromfile='z:/tmp/file.xml')
```

Thank you.

**Comment by dr-leo** [comment]
Hi,

this is possible. See sec. 5.3.3. of the docs and the doc string of
pandasdmx.Request.get method. The docs are not very clear though. I will
make this feature a bit more visible.

You could try

r=Request()
response=r.get(url = myurl)

myurl must comply with the REST interface of, e.g., Banca d'Italia. If
you pass an 'url' kwarg, all the other args used to have the get method
construct the URL for you are ignored. So you have to know the rules of
the REST interface yourself. This is not very convenient, of course.

However, if Banca d'Italia offers a REST interface similar to ECB or
ESTAT, I am happy to add it to the next release. A PR would be welcome.
You'd have to add it to api.py like the other agencies.

Leo


Am 19.04.2016 um 17:27 schrieb esvhd:

**Comment by esvhd** [comment]
Hi Leo,

I did the following, however, it seemed that `res.msg.data.series` was empty..

```python
import pandasdmx as sdmx

req = sdmx.Request()
res = req.get(url='https://a2a.bancaditalia.it/infostat/dataservices/export'
              '/EN/SDMXv21/DATA/CUBE/BANKITALIA/DIFF/FSI')

# the following line returns an empty list..
[s for s in res.msg.data.series]
>>> []
```

Not sure it actually received any data. Can I actually use `req.get(fromfile='xxx'` instead? After I call `get()`, how can I actually get the data out into a frame? 

Very new to SDMX, would love to contribute but that might take a while... 

Is it possible to have an easy interface to convert data into a dataframe? Something like **`response.to_frame()`**? Just an idea, I don't really know if there's anything in SDMX format that prevents you from doing so.

Thank you @dr-leo !

**Comment by dr-leo** [comment]
I recommend experimenting with ECB first. On pd dataframe read the code examples. 
Your link does not point to an sdmx resource. Hence the empty response.

**Comment by dr-leo** [comment]
Closing this. See https://github.com/dr-leo/pandaSDMX/issues/34 instead.

**Comment by dr-leo** [comment]
Hi,

Request objects now have a 'load_agency_profile() method allowing the user to Register custom agency metadata in JSON Format. This opens a playground for users to make request to data Providers not hard-coded in pandaSDMX. Banca d'Italia might be a good starting-point. Another might be the UK Office for National Statistics. To see how a metadata record for an agency should be structured, see the built-in metadata in 'pandasdmx.agencies.json'. 

Note that this Feature has not been released yet. You have to get the current version from the repo.

**Comment by dr-leo** [comment]
PS: I would gladly add ISTAT as built-in data Provider. But I doubt that I can test it as I have no user credentials, nor fixed IP address. So please feel free to send a PR or let me know otherwise how to do it if you're still interested.

Thanks.

Leo

**Comment by dr-leo** [comment]
Done with help from ISTAT staff.
