### ISSUE TITLE
Problem with ``req.categoryscheme()``

### ISSUE THREAD

**Issue by toobaz** [dr-leo/pandaSDMX#36]
```
req = Request('ESTAT')
req.categoryscheme()
```

raises ``AttributeError: __exit__`` because [http://ec.europa.eu/eurostat/SDMX/diss-web/rest/categoryscheme](http://ec.europa.eu/eurostat/SDMX/diss-web/rest/categoryscheme) gives a "501 - Not Implemented" error.

Curiously, if the provider is ``ECB`` the problem doesn't arise... although it does in the [automatically generated documentation](http://pandasdmx.readthedocs.io/en/master/usage.html#overview)!

**Comment by dr-leo** [comment]
Right. ESTAT for some obscure reason does not support categoryschemes.
This is mentioned in pandasdmx docs. What else can we do about it?


Am 23.05.2016 um 12:14 schrieb Pietro Battiston:

**Comment by toobaz** [comment]
OK, funny.

I indeed had missed this mention of ESTAT in the docs. But what had pushed me to submit this bug was simply that the ECB examples in the docs I linked to were also exhibiting the same problem yesterday! Since in the meanwhile the docs were updated and now the problem disappeared... I guess we are back to the "there is not much we can do" scenario, and this can be closed
