### ISSUE TITLE
Multiple .dist-info directories error

### ISSUE THREAD

**Issue by BadWizard** [dr-leo/pandaSDMX#38]
I am trying to install with `pip install pandasdmx` in a conda environment with Python3.5. I get this error message.

AssertionError: Multiple .dist-info directories: /Users/BadWizard/anaconda3/envs/py35/lib/python3.5/site-packages/pandaSDMX-0.5.dist-info, /Users/BadWizard/anaconda3/envs/py35/lib/python3.5/site-packages/pandaSDMX-0.5.1.dist-info

**Comment by dr-leo** [comment]
Sorry. It should be fixed now; uploaded 0.5.2 with bild dir deleted
prior to building the wheel.

I consider this a terrible bug in the build tool chain.

Pls let me know if you still encounter a problem.

Leo

Am 30.10.2016 um 13:57 schrieb BadWizard:

**Comment by BadWizard** [comment]
Now it works, thanks a lot.
