### ISSUE TITLE
Problem with INSEE: freq isn't recognized

### ISSUE THREAD

**Issue by jmarrec** [dr-leo/pandaSDMX#39]
Hi,

First, thanks for your work!

Second, I'm having problem querying the INSEE. I'm following the guide:

```
insee = Request('INSEE')
data_response = insee.data(resource_id = 'DEFM-CAT', 
                           key={'CORRECTION': 'BRUT',
                                'CAT-DE': 'A+B+C+D+E',})
data = data_response.data
```

It seems that the FREQ isn't recognized:

```
> set(s.key.FREQ for s in data.series)
AttributeError: 'SeriesKey' object has no attribute 'FREQ'
```

```
> data_response.write()
UnboundLocalError: local variable 'freq_key' referenced before assignment
```

But if you look at http://www.bdm.insee.fr/series/sdmx/data/DEFM-CAT, there is the FREQ keyword, e.g.:

```
<Series CAT-DE="A" GEOGRAPHIE="FM" CORRECTION="BRUT" FREQ="M" IDBANK="001572432" TITLE="Demandeurs d'emploi inscrits en fin de mois à Pôle emploi - Catégorie A - France métropolitaine - Série brute" LAST_UPDATE="2016-11-24" UNIT_MEASURE="IND" UNIT_MULT="3" REF_AREA="FM" DECIMALS="1" TIME_PER_COLLECT="FIN">
```

Am I missing something obvious?

Thanks!

**Comment by dr-leo** [comment]
Hi,

there is nothing wrong: FREQ is not a dimension name but an attribute
name at series level. Try something like:

l = list(data_response.series)
l[0].attrib

Btw: To generate a pandas DataFrame from this data set, do something like

df = data_response.write(parse_time=False)

This DataFrame has a string index, not a datetime or period index. But
you can generate one using pandas magic.

Leo

Am 26.11.2016 um 15:35 schrieb Julien Marrec:
