### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by vincemat** [dr-leo/pandaSDMX#48]
Hi,

My project was working fine untill today afternoon...
Since then, the following code is reporting an "AttributeError: __exit__"

```
from pandasdmx import Request
esta = Request('ESTAT')
une_resp = esta.get('data','demo_gind')
```

I attached a printscreen of the error:

![capture-python](https://cloud.githubusercontent.com/assets/12695531/23874808/4785edae-0837-11e7-961f-84ee550f8881.PNG)

Do you have an idea of the source of the issue ?

Thank you

**Comment by dr-leo** [comment]
Hi,

I will gladly look at your problem once you send me a code example
copy-pasted into the message rather than a screenshot.

Thanks.

Leo


Am 13.03.2017 um 21:53 schrieb Vincent Matton:

**Comment by vincemat** [comment]
Hi Leo,

Thank you for your quick answer.
The code is very simple (as in my previous message) : 

```
from pandasdmx import Request
esta = Request('ESTAT')
une_resp = esta.get('data','demo_gind')
```

Thanks,

Vincent

**Comment by dr-leo** [comment]
Pls send the traceback. Thanks.

**Comment by vincemat** [comment]
I retry to run the script right now and it seems to work... 
It was maybe an issue with the Eurostat server as I noticed that I wasn't able to connect to it with other Python scripts this morning...

Anyway, thank you for your support !!
