### ISSUE TITLE
Add World Bank as new agency

### ISSUE THREAD

**Issue by davidbailey** [dr-leo/pandaSDMX#52]
The World Bank "World Integrated Trade Solution" is available vis SDMX. The user guide is available here: http://wits.worldbank.org/data/public/WITSAPI_UserGuide.pdf. The following block seems to work.
`
        'WBG_WITS': {
            'name': 'WBG_WITS',
            'url': 'http://wits.worldbank.org/API/V1/SDMX/V21/rest',
            'resources': {
                'data': {
                    'headers': {},
                },
            }
        },
`

**Comment by dr-leo** [comment]
Thanks. Have you been able to make a request? Please note that in the
dev Version on github you can not pass a json string to a method of
Request class, I believe it is named add_agency or something. So you
can add the WITS agency manually and make all Kinds of requests.

I would be very happy to add the agency if it works.

It appears that other data offerings of WB have an SDMX API as well.
But docs are poor, eg. which SDMX Version is unclear.

Thanks again!

Leo

**Comment by davidbailey** [comment]
Hey Leo,

Yes, it works well. I've simply added the above config to my local api.py file. I'm running pandaSDMX 0.6.1 installed via pip so I'm a little behind what is here on GitHub. Below is an example based on your documentation. The API documentation is at http://wits.worldbank.org/data/public/WITSAPI_UserGuide.pdf.

Thanks,
David

```
wits = Request('WBG_WITS')
cat_response = wits.categoryscheme()
dsd_id = cat_response.dataflow['DF_WITS_TradeStats_Trade'].structure.id
dsd_response = wits.datastructure(resource_id = dsd_id)
dsd = dsd_response.datastructure[dsd_id]
dsd.dimensions.aslist()

data_response = wits.data(resource_id = 'DF_WITS_TradeStats_Trade', key = {'FREQ': 'A', 'REPORTER': 'DEU', 'PARTNER': 'USA', 'PRODUCTCODE': 'Fuels', 'INDICATOR': 'XPRT-TRD-VL'}, params = {})
```

**Comment by dr-leo** [comment]
Hi David,


thanks. Looks awesome. It will go into v0.7 to be relased in a few days
- hopefully.


Leo


Am 09.06.2017 um 11:40 schrieb David Bailey:

**Comment by dr-leo** [comment]
btw: You don't need to query the category-scheme. You need the dataflows
so you con do:


>>> flows_resp = wits.dataflow()


Then select the dataflow you want, extract the DSD ID etc.


The docs may be a bit misleading.


Am 09.06.2017 um 11:40 schrieb David Bailey:
