### ISSUE TITLE
unqualified exec is not allowed

### ISSUE THREAD

**Issue by HristoBuyukliev** [dr-leo/pandaSDMX#55]
`from pandasdmx import Request`

gives me the error 

`File "/home/hristo/mlenv/local/lib/python2.7/site-packages/pandasdmx/utils/anynamedtuple.py", line 156
    exec(class_definition, namespace)
SyntaxError: unqualified exec is not allowed in function 'namedtuple' it contains a nested function with free variables`

Here is the "pip freeze" output:
>alembic==0.9.3
algopy==0.5.5
Babel==2.3.4
backports-abc==0.5
backports.csv==1.0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
backports.weakref==1.0rc1
beautifulsoup4==4.4.1
bleach==1.5.0
blinker==1.3
certifi==2017.4.17
chardet==3.0.4
click==6.6
configparser==3.5.0
cycler==0.10.0
decorator==4.0.11
entrypoints==0.2.3
enum34==1.1.6
extras==0.0.3
fixtures==2.0.0
Flask==0.11.1
Flask-Babel==0.11.1
Flask-Gravatar==0.4.2
Flask-HTMLmin==1.2
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Migrate==2.0.3
Flask-Principal==0.4.0
Flask-Script==2.0.5
Flask-Security==1.7.5
Flask-SQLAlchemy==2.1
Flask-WTF==0.12
funcsigs==1.0.2
functools32==3.2.3.post2
html5lib==1.0b3
htmlmin==0.1.10
idna==2.5
importlib==1.0.4
inflection==0.3.1
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==6.0.0
itsdangerous==0.24
Jinja2==2.7.3
jsonpath-rw==1.4.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
Keras==2.0.6
linecache2==1.0.0
lxml==3.8.0
Mako==1.0.6
Markdown==2.6.8
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.7.4
mock==2.0.0
more-itertools==3.2.0
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
numdifftools==0.9.20
numpy==1.13.1
pandas==0.20.3
pandas-datareader==0.5.0
pandaSDMX==0.7.0
pandocfilters==1.4.1
passlib==1.6.2
pathlib2==2.3.0
patsy==0.4.1
pbr==1.9.1
pexpect==4.2.1
pgadmin4==1.5
pickleshare==0.7.4
ply==3.10
prompt-toolkit==1.0.14
protobuf==3.3.0
psycopg2==2.7.1
ptyprocess==0.5.2
pycrypto==2.6.1
pyflux==0.4.15
pyforecast==1.0
Pygments==2.2.0
pyparsing==2.2.0
pyrsistent==0.11.13
python-dateutil==2.6.1
python-editor==1.0.3
python-mimeparse==1.5.1
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
Quandl==3.2.0
requests==2.17.3
requests-file==1.4.2
requests-ftp==0.3.1
rpy2==2.8.6
scandir==1.5
scikit-learn==0.18.2
scipy==0.19.1
seaborn==0.8
simplegeneric==0.8.1
simplejson==3.6.5
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
speaklater==1.3
SQLAlchemy==1.0.14
sqlparse==0.1.19
statsmodels==0.8.0
subprocess32==3.2.7
tensorflow==1.2.1
terminado==0.6
testpath==0.3.1
testtools==2.3.0
Theano==0.9.0
tornado==4.5.1
tqdm==4.14.0
traceback2==1.4.0
traitlets==4.3.2
unittest2==1.1.0
urllib3==1.21.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.9.6
widgetsnbextension==2.0.0
WTForms==2.0.2
xgboost==0.6a2

**Comment by dr-leo** [comment]
Try updating python

**Comment by HristoBuyukliev** [comment]
Yes, it seems to work in python3 and not python2. Maybe some indication in the documentation?

**Comment by dr-leo** [comment]
Python 2.7.10+ should work as well.

**Comment by HristoBuyukliev** [comment]
Right. Thanks.
