### ISSUE TITLE
Issue with IMF

### ISSUE THREAD

**Issue by ScharcoMolten** [dr-leo/pandaSDMX#56]
Hi Dr. Leo,

Thank you for developing the very useful pandasdmx tool!

Unfortunately I'm having some issues downloading data from the IMF database. Choosing the right codes from the codelists worked so far,  but putting them into the response function leads to an empty sheet : 

`import pandasdmx`
`from pandasdmx import Request`
`imf = Request('IMF_SDMXCENTRAL')`
`resp = imf.data('UEM', key = {'REF_AREA':'AT'})`
`data = resp.write()`
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-8ccba3e6ac87> in <module>()
----> 1 data = resp.write()

C:\ProgramData\Anaconda3\lib\site-packages\pandasdmx\api.py in write(self, source, **kwargs)
    633         if not source:
    634             source = self.msg
--> 635         return self._writer.write(source=source, **kwargs)
    636 
    637     def write_source(self, filename):

C:\ProgramData\Anaconda3\lib\site-packages\pandasdmx\writer\data2pandas.py in write(self, source, asframe, dtype, attributes, reverse_obs, fromfreq, parse_time)
    114                     pd_series, pd_attributes = zip(*series_list)
    115                 elif dtype:
--> 116                     key_fields = series_list[0].name._fields
    117                     pd_series = series_list
    118                 elif attributes:

IndexError: list index out of range
```

When I try to get an overview over the dataset, this happens : 
`data = resp.data`
`data.columns.names`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-0786dd9c8bac> in <module>()
----> 1 data.columns.names

AttributeError: 'DataSet' object has no attribute 'columns'
```
`data.series`
`series_l = list(data.series)[]`

It seems, as if the dataset I'm downloading is empty. I have tested the same code with data from estat and had no problems to use it.
Do you have any advice what's wrong ? 

With best regards,
Marco

**Comment by dr-leo** [comment]
Hi Marco,


probably the IMF just sent you an empty data set because there is no
data on Austria. Maybe the entire data set is empty. You could check
this by wildcarding the area dimension while keeping the potential size
small setting a reasonable startPeriod.


SDMXCentral is merely a side project of the stats division at the IMF.
Two insiders told me that there is few data in there. The complete data
is accessible via a SOAP API not supported by pandaSDMX, yet.


Cheers,


Leo




Am 07.09.2017 um 15:52 schrieb ScharcoMolten:

**Comment by ScharcoMolten** [comment]
Hi Leo,

thanks for your fast answer. 
Changing the code  and putting a reasonable start period didn't solve the issue, but thanks for your Information on SDMXCentral. 

With best regards,
Marco

**Comment by dr-leo** [comment]
I hope support for the main IMF data access point can be added soon.
