### ISSUE TITLE
Add support for other SDMX data sources.

### ISSUE THREAD

**Issue by johnny555** [dr-leo/pandaSDMX#6]
It doesn't seem possible to use a SDMX agency other than the default ESTAT, ECB and ILO.

Can support for any SDMX website be built?

**Comment by dr-leo** [comment]
Any SDMX agency can be supported that generates SDMX 2.1-compliant
messages. The only agencies I know of that deliver data in SDMX 2.1 are
ECB and Eurostat. I will remove the mention of ILO from the docs. If you
are aware of any other fully 2.1-compliant agency, please let me know.

Support for SDMX 2.0 messages could be added as a new reader module.
Perhaps the model would have to be tweaked a bit as well; I haven't
checked this. Anyway, it would take me a couple of weeks to do that. And
I don't have time for this along with my dayjob; I am not paid for this
SDMX stuff. But I am happy to consider any PR's. 2.0 would give you
access to ILO, FAO, IMF, OECD, and maybe Worldbank. OECD seems to move
to SDMX-JSON. So a JSON reader would seem useful.



 


Am 15.04.2015 um 08:00 schrieb John Vial:

**Comment by dr-leo** [comment]
Closing this as it is covered by other issues / enhancement proposals.
