### ISSUE TITLE
Frequency issue with Insee data

### ISSUE THREAD

**Issue by louisdecharson** [dr-leo/pandaSDMX#63]
Hi,

I am trying to download data from INSEE but I have troubles downloading IPCH data.
When trying to retrieve data, I have the following error:
```
/~/python3.5/site-packages/pandas/core/indexes/period.py in _assert_can_do_setop(self, other)
    955         if self.freq != other.freq:
    956             msg = _DIFFERENT_FREQ_INDEX.format(self.freqstr, other.freqstr)
--> 957             raise IncompatibleFrequency(msg)
    958 
    959     def _wrap_union_result(self, other, result):

IncompatibleFrequency: Input has different freq=M from PeriodIndex(freq=A-DEC)
```
Here is a MWE to reproduce the error:
```
from pandasdmx import Request
insee = Request('INSEE')
ipch = 'IPCH-2015'
data = insee.data(resource_id = ipch,key={'FREQ':'M','COICOP2016':'032'})
```

Thank you very much!

cc @Asigwalt

**Comment by dr-leo** [comment]
Hi,

you are attempting to generate a DataFrame from series with different frequencies (in this case 'A' and 'M').

You can see this by issuing:

>>> set(s.key.FREQ for s in data.data.series)

Of course you have to download the data set and store it in `data` by deleting `.write().to_html()`. The big question is how a series with 'A' frequency can be returned given that you specify 'M' as FREQ. This could be a bug on the part of INSEE's server.  

A similar example including a workaround can
be found in the tutorial at

http://pandasdmx.readthedocs.io/en/latest/usage.html#selecting-columns-using-the-model-api

So this is a feature rather than a bug. Admittedly, the error message can be made more helpful. I will think about this idea.

Leo

**Comment by louisdecharson** [comment]
Hi,

Thank you very much for making this more clear. Indeed, I was looking for something to restrict frequency to monthly data _a priori_. Anyway, I will use the workaround! Thank you very much!

By the way, I think the bug is on your side as I am able to get the request right on [sdmx.herokuapp.com](http://sdmx.herokuapp.com/insee/dataset/IPCH-2015?COICOP2016=032&FREQ=M)


Best,

Louis

**Comment by louisdecharson** [comment]
PS: request on `bdm.insee.fr` seems to work well:
[https://bdm.insee.fr/series/sdmx/data/IPCH-2015/M.IPCH.032..........](https://bdm.insee.fr/series/sdmx/data/IPCH-2015/M.IPCH.032..........)

**Comment by louisdecharson** [comment]
For some reason, it seems that frequency is not taken into account.  You can see this by trying to retrieve non-existence time-series (in order to produce error 404 which incidentally prints the insee's url)

Trying this code:
```python
from pandasdmx import Request
options = {
    'FREQ':'A',
    'NATURE':'POND',
    'REF_AREA':'FE',
    'BASIND':'2015',
    'UNIT_MEASURE':'SO',
    'CORRECTION':'BRUT',
    'INDICATEUR':'IPCH',
    'COICOP2016':'032'
}
data_response = Request('INSEE').data(resource_id = 'IPCH-2015',key=options)
```
 
It fails with this `error 404`:
```python
HTTPError: 404 Client Error:  for url: https://bdm.insee.fr/series/sdmx/data/IPCH-2015/.IPCH.032.POND...BRUT.2015
```
while it should fail imo with this `error 404`:
```python
HTTPError: 404 Client Error:  for url: https://bdm.insee.fr/series/sdmx/data/IPCH-2015/A.IPCH.032.POND...BRUT.2015
```

**Comment by dr-leo** [comment]
Would you mind reporting this bug (missing codelist for FREQ Dimension) to INSEE so they can fix it?

The next release of pandaSDMX will be more graceful and add the 'A' to the key string even if it could not be validated against the codelist. I will commit it shortly. I'll Close this now.

Thanks again for spotting this.

Leo
