### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rudolf-bauer** [dr-leo/pandaSDMX#65]
Hi,

when executing this simple example with the subscription header params as specified in the [UNESCO docs](https://apiportal.uis.unesco.org/getting-started) I get an error.
```
from pandasdmx import Request
request = Request('UNESCO', headers={'Ocp-Apim-Subscription-Key': 'XXX'})
symbol= 'UNESCO,CE,1.0/EDU.._T.._T.._T........'
response = request.data(symbol)
df = response.write()
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-21-5b250bcfe1a0> in <module>()
----> 1 df = response.write()

/usr/local/lib/python3.6/site-packages/pandasdmx/api.py in write(self, source, **kwargs)
    633         if not source:
    634             source = self.msg
--> 635         return self._writer.write(source=source, **kwargs)
    636 
    637     def write_source(self, filename):

/usr/local/lib/python3.6/site-packages/pandasdmx/writer/data2pandas.py in write(self, source, asframe, dtype, attributes, reverse_obs, fromfreq, parse_time)
    114                     pd_series, pd_attributes = zip(*series_list)
    115                 elif dtype:
--> 116                     key_fields = series_list[0].name._fields
    117                     pd_series = series_list
    118                 elif attributes:

IndexError: list index out of range
```

It seems as if no data could be extracted from the response, since `series_list` is empty. The error still occurs, when I'm using the subscription key as a URL param: `UNESCO,CE,1.0/EDU.._T.._T.._T........?subscription-key=XXX`. However, when I request the URL in the browser the data seems to be fine. `http://api.uis.unesco.org/sdmx/data/UNESCO,CE,1.0/EDU.._T.._T.._T........?subscription-key=XXX` (replace with your key).

Thanks in advance,

Rudi

**Comment by dr-leo** [comment]
Hi, thanks for this book report. But I do not have a subscription key anymore for UNESCO, could you please send me the XML file which produces the error? You can easily save it locally using the right source method of the the response object.

**Comment by rudolf-bauer** [comment]
Sure, here is the corresponding xml. I compared it to the xml obtained using the URL in my browser and the `message:DataSet` elements seem to be identical.

**Comment by dr-leo** [comment]
Unfortunately the attachment was stripped off I think by github. Could you resend the message directly to my email address? By the way I was wondering if you are using the latest release version 0.8.2. I think I had fixed a bug in the rightr causing index errors in case offempty serious.

**Comment by dr-leo** [comment]
I still tend to believe the Format is inconsistent with the SDMX Standard. So I do not see how to fix this other than alerting the Provider (Unfortunately, I do not have the time to do this). Please re-open if you disagree.

Leo
