### ISSUE TITLE
ENH: add SDMX-JSON reader  

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#7]
The SDMX community is working on a JSON alternative to XML-based SDMX-ML. 

https://github.com/sdmx-twg

The data-related parts are in an advanced stage. The OECD is using this draft format in beta mode. The ECB uses it as well although we do not depend on it as ECB also offers XML. The OECD offers SDMX-2.1 data as JSON only. Thus, a reader for JSON would give pandaSDMX immediate access to OECD data. More agencies are likely to adopt JSON as a simpler replacement for XML.

An SDMX-JSON reader for pandaSDMX is thus a high priority. It could be implemented as follows:

1. start from a copy of data2pandas.py
2. Use 
https://pypi.python.org/pypi/jsonpath-rw/

instead of LXML. The XPath expressions would have to be replaced by their function jsonpath equivalents, if possible. I haven#t checked this.

3. Perhaps tweak the reader methods to properly interact with jsonpath.

4. api.py: extend the metadata on agencies by adding a 'reader# item so that each agency may be assigned a reader class. The get_reader method needs to be adjusted; currently it instantiates the only reader as there is no choice anyway.

5. Test with sample data provided on the github page of the SDMX Technical Working Group

**Comment by toasteez** [comment]
Re 3. Test with sample data provided on the github page of the SDMX Technical Working Group .  Can you add a link to the data I had a look at https://github.com/sdmx-twg , but to me it was not obvious as to what data I should be referring to?

**Comment by dr-leo** [comment]
Check out the repo at
https://github.com/sdmx-twg/sdmx-json

and look at the subdir
'data-message/samples'.
 
 

Am 08.07.2015 um 19:51 schrieb toasteez:

**Comment by dr-leo** [comment]
This is largely completed and will be part of v0.5.
