### ISSUE TITLE
request from file

### ISSUE THREAD

**Issue by ktroutman** [dr-leo/pandaSDMX#71]
Hi,

Trying to load an existing SDMX-XML file from disk using pandasdmx.Request.get(fromfile=file), but receiving the following error message: get() missing 1 required positional argument: 'self'

Reading the docs, it wasn't entirely clear how this is to be done. Could you advise?

Thanks!

**Comment by dr-leo** [comment]
You must instantiate a Request object before calling ist get method:

pandasdmx.Request().get(...)

**Comment by ktroutman** [comment]
Of course. Thanks!

**Comment by digrks** [comment]
Hi I had the above issue as well and when trying the above solution: 
pandasdmx.Request().get(fromfile=r"C:\****\Downloads\******Sample.sdmx21.xml")

I get: ValueError: If `` url`` is not specified, either agency or fromfile must be given.
