### ISSUE TITLE
Annotation titles: "title" vs "AnnotationTitle"

### ISSUE THREAD

**Issue by brockfanning** [dr-leo/pandaSDMX#77]
Hello, I'm trying to read a [DSD](https://unstats.un.org/sdgs/files/SDG_DSD.xml) which has annotations with "AnnotationTitle" instead of "title" (which this library [expects](https://github.com/dr-leo/pandaSDMX/blob/master/pandasdmx/model.py#L126)). I don't know enough about SDMX to know which is correct. What do you think - should I submit a PR here to change it to 'AnnotationTitle'? Or should that DSD from the UN be using 'title' instead?

**Comment by khaeru** [comment]
@brockfanning thanks for reporting the issue!

To be clear, there is a major refactor going on over in #72 —if you feel brave enough to play around with the code on that branch, could you report whether it solves this issue for you?

I believe it should; the reason is that there is a test that a specific snippet of UNSD XML can be parsed: [unsd_codelist_partial.xml](https://github.com/dr-leo/pandaSDMX/blob/dba2d5c93cbad4145ee196c26cd215a7acdc85fa/tests/data/common/unsd_codelist_partial.xml). This contains the AnnotationTitle XML elements that you refer to. The test passes, so I think this means that the refactored XML parser can handle that element.

**Comment by brockfanning** [comment]
@khaeru Cool, thanks for the info. Let me know if I should post this at #72, but using that branch gives me an error when I attempt the `import pandasdmx`. Here is the output:

```
/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/remote.py:12: RuntimeWarning: optional dependency requests_cache is not installed; cache options to Session() have no effect
  'to Session() have no effect', RuntimeWarning)
Traceback (most recent call last):
  File "/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/util.py", line 10, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 24, in <module>
    import pandasdmx
  File "/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/__init__.py", line 1, in <module>
    from pandasdmx.api import Request, open_file
  File "/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/api.py", line 17, in <module>
    from .model import DataStructureDefinition, IdentifiableArtefact
  File "/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/model.py", line 43, in <module>
    from pandasdmx.util import (
  File "/home/brockfanning/.local/share/virtualenvs/foo-rhErfScv/src/pandasdmx/pandasdmx/util.py", line 15, in <module>
    from typing import _alias
ImportError: cannot import name '_alias'
```

The above is from running a script that just contains:
```
import pandasdmx
```

And the Pip file for the project is:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pandasdmx = {editable = true,git = "https://github.com/khaeru/pandaSDMX.git",ref = "refactor"}

[requires]
python_version = "3.6"
```

Thank you for any tips!

**Comment by brockfanning** [comment]
Disregard the above -- I read the docs in the branch and realized that Python 3.6 is not supported.

I can confirm, after trying with Python 3.7, that #72 does resolve the AnnotationTitle issue mentioned above.

**Comment by khaeru** [comment]
Great, glad to hear that the code on the branch doesn't suffer from this issue. We'll try to get that merged and a release out ASAP in order to have it available in the PyPI version.
