### ISSUE TITLE
Add examples/tests of multiple Constraints

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#81]
Per @dr-leo e-mail discussion re: #72, Constraints may exist in multiple places simultaneously; i.e. attached to a DataStructureDefinition (DSD); a DataflowDefinition (DFD) that references the DSD; a ProvisionAgreement, etc.

As a precondition for ensuring that the code handles these properly, we need SDMX-ML specimens/examples that include multiple constraints, and tests that check how they are handled.

**Comment by dr-leo** [comment]
Arguably obsolete.
