### ISSUE TITLE
Constrain single Dimensions

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#82]
#72 implemented one type of Constraint—the CubeRegion—through `__contains__` methods on MemberSelection and CubeRegion:
https://github.com/dr-leo/pandaSDMX/blob/a670198f45f90777d26b5b83c8d9e171b266ff6b/pandasdmx/model.py#L618-L637
This allows the evaluation of `k in cr`, when `k` is an instance of Key, and `cr` is an instance of CubeRegion.

A related, but distinct, task is to get all possible valid KeyValues for _only one_ of the Dimensions of the CubeRegion. In pandaSDMX 0.9 this was used for validating queries; in 1.x, it is not used for this purpose, but the feature would still be useful.

**Comment by dr-leo** [comment]
Is the above comment still current, i.e. are keys for data requests validated against the unconstrained codelists?

**Comment by dr-leo** [comment]
While I consider this feature as a must-have, I am fine with the 1.1 Milestone.

**Comment by dr-leo** [comment]
Obsolete.
