### ISSUE TITLE
Provide conda package on conda-forge

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#83]
Need to check first if all dependencies are available as conda packages.

**Comment by ChristopherShort** [comment]
Looks like everything except jsonpath-rw - at least in main, conda-forge or conda-canary.

All others (up to date) seem available from the 'main' (defaults) channel

cheers

**Comment by dr-leo** [comment]
Thanks. The current development version in the master branch does not depend onjsonpath though. It depends on pydantic instead.

**Comment by dr-leo** [comment]
The [instructions](https://conda-forge.org/docs/maintainer/adding_pkgs.html) seem straitforward. In a nutshell: 
* build a release on GitHub
* generate the conda recipe following the instructions. Need to decide on the Tests to run during each build
* make a PR on conda-forge for review by the conda-forge Team who may or may not make suggestions or request changes 

Note that maintaining a conda-forge feedstock comprises a number of Tasks as described in the instructions.

**Comment by dr-leo** [comment]
Development of a conda recipe with the ultimate goal to make pandasdmx available on conda/forge should take place in [this repo](https://github.com/dr-leo/staged-recipes).

**Comment by dr-leo** [comment]
Done. See https://github.com/dr-leo/pandasdmx-feedstock
