### ISSUE TITLE
Reconfigure 0.9 docs build on RTD

### ISSUE THREAD

**Issue by khaeru** [dr-leo/pandaSDMX#84]
As raised by @dr-leo:

0.9 was released from the branch `current_stable`, which was only later merged into `master` (#73). However, there is no git tag or Github release for 0.9. So ReadTheDocs is only building `master` (also accessible by the `latest` pointer), i.e. pre-1.0.

Steps to resolve:
- [x] Create a tag/Github release for 0.9, probably on commit 16950d60fd7be933543cff2c26e8a11e1fd7433e
- [x] Enable RTD build of this version of the docs.
- [x] Set the `stable` pointer on RTD to be this version, and point visitors to `stable` by default.

**Comment by khaeru** [comment]
The above steps are done; I will also modify the README to point to both versions.

**Comment by dr-leo** [comment]
Thanks.
